import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";

const servicePath = path.resolve(process.cwd(), "src/services/admin-ingestion.ts");

test("admin ingestion list over-fetches before derived filters and returns requested page size", async () => {
  const src = await fs.readFile(servicePath, "utf8");

  assert.match(src, /function usesDerivedListFilter\(options: ListIngestionDocumentsOptions\)/);
  assert.match(src, /function usesDerivedListSort\(sort: ListIngestionDocumentsOptions\["sort"\]\)/);
  assert.match(src, /function likelyFixtureSqlExclusionClause\(\)/);
  assert.match(src, /if \(options\.realOnly\) \{\s*where\.push\(likelyFixtureSqlExclusionClause\(\)\)/);
  assert.match(src, /function runtimeManualCandidateSqlPrefilterClause\(\)/);
  assert.match(src, /BETWEEN 1 AND 2/);
  assert.match(src, /if \(options\.runtimeManualCandidatesOnly\) \{\s*where\.push\(runtimeManualCandidateSqlPrefilterClause\(\)\)/);
  assert.match(src, /function approvalReadySqlPrefilterClause\(\)/);
  assert.match(src, /function approvalReadinessScoreSqlExpr\(\)/);
  assert.match(src, /CASE WHEN d\.file_type <> 'decision_docx' THEN 1 ELSE 0 END/);
  assert.match(src, /CASE WHEN COALESCE\(d\.qc_required_confirmed, 0\) = 0 THEN 1 ELSE 0 END/);
  assert.match(src, /CASE WHEN \$\{unresolvedReferenceCount\} > \$\{approvalUnresolvedThresholdSqlExpr\(\)\} THEN 1 ELSE 0 END/);
  assert.match(src, /round\(min\(20, \$\{extractionConfidence\} \* 20\)\)/);
  assert.match(src, /case "approvalReadinessDesc":\s*return "approvalReadinessScore DESC, created_at DESC"/);
  assert.match(src, /\$\{approvalReadinessScoreSqlExpr\(\)\} as approvalReadinessScore/);
  assert.match(src, /d\.qc_required_confirmed = 1/);
  assert.match(src, /d\.approved_at IS NULL/);
  assert.match(src, /WHEN \$\{limitedPilotConfirmed\} THEN 5/);
  assert.match(src, /if \(options\.approvalReadyOnly\) \{\s*where\.push\(approvalReadySqlPrefilterClause\(\)\)/);
  assert.match(src, /function approvalBlockerSqlPrefilterClause\(blocker: string \| undefined\)/);
  assert.match(src, /case "metadata_not_confirmed":\s*return "COALESCE\(d\.qc_required_confirmed, 0\) = 0"/);
  assert.match(src, /case "unresolved_references_above_threshold":\s*return `\$\{unresolvedReferenceCount\} > \$\{approvalUnresolvedThresholdSqlExpr\(\)\}`/);
  assert.match(src, /function reviewerReadySqlPrefilterClause\(\)/);
  assert.match(src, /function reviewerReadySqlPrefilterClause\(\)[\s\S]*COALESCE\(d\.qc_required_confirmed, 0\) = 0/);
  assert.match(src, /function reviewerReadySqlPrefilterClause\(\)[\s\S]*drl\.reference_type = 'index_code'/);
  assert.match(src, /function reviewerReadySqlPrefilterClause\(\)[\s\S]*drl\.reference_type = 'rules_section'/);
  assert.match(src, /function reviewerReadySqlPrefilterClause\(\)[\s\S]*drl\.reference_type = 'ordinance_section'/);
  assert.match(src, /function reviewerReadinessSortScoreSqlExpr\(\)/);
  assert.match(src, /return `CASE WHEN \$\{reviewerReadySqlPrefilterClause\(\)\} THEN 1 ELSE 0 END`/);
  assert.match(src, /case "reviewerReadinessDesc":\s*return `\$\{reviewerReadinessSortScoreSqlExpr\(\)\} DESC, approvalReadinessScore DESC, created_at DESC`/);
  assert.match(src, /case "reviewerEffortAsc":\s*return "unresolvedReferenceCount ASC, approvalReadinessScore DESC, created_at DESC"/);
  assert.match(src, /case "batchabilityDesc":\s*return "unresolvedReferenceCount DESC, approvalReadinessScore DESC, created_at DESC"/);
  assert.match(src, /case "unresolvedLeverageDesc":\s*return "unresolvedReferenceCount ASC, approvalReadinessScore DESC, created_at DESC"/);
  assert.match(src, /case "blocked37xBatchKeyAsc":\s*return "unresolvedUnsafe37xCount DESC, unresolvedReferenceCount DESC, created_at DESC"/);
  assert.match(src, /if \(options\.reviewerReadyOnly\) \{\s*where\.push\(reviewerReadySqlPrefilterClause\(\)\)/);
  assert.match(src, /function reviewerRiskSqlPrefilterClause\(riskLevel: ListIngestionDocumentsOptions\["reviewerRiskLevel"\]\)/);
  assert.match(src, /if \(riskLevel === "low" \|\| riskLevel === "medium"\) return reviewerReadySqlPrefilterClause\(\)/);
  assert.match(src, /const reviewerRiskSqlPrefilter = reviewerRiskSqlPrefilterClause\(options\.reviewerRiskLevel\)/);
  assert.match(src, /if \(reviewerRiskSqlPrefilter\) \{\s*where\.push\(reviewerRiskSqlPrefilter\)/);
  assert.match(src, /function estimatedReviewerEffortSqlPrefilterClause\(effort: ListIngestionDocumentsOptions\["estimatedReviewerEffort"\]\)/);
  assert.match(src, /if \(effort === "low"\) return `\$\{unresolvedReferenceCount\} <= 2`/);
  assert.match(src, /if \(effort === "medium"\) return `\$\{unresolvedReferenceCount\} > 2`/);
  assert.match(src, /if \(effort === "high"\) return `\$\{unresolvedReferenceCount\} > 0`/);
  assert.match(src, /const estimatedReviewerEffortSqlPrefilter = estimatedReviewerEffortSqlPrefilterClause\(options\.estimatedReviewerEffort\)/);
  assert.match(src, /if \(estimatedReviewerEffortSqlPrefilter\) \{\s*where\.push\(estimatedReviewerEffortSqlPrefilter\)/);
  assert.match(src, /function recurringCitationFamilySqlPrefilter\(family: string \| undefined\): \{ clause: string; binds: string\[\] \} \| null/);
  assert.match(src, /const normalizedFamily = stripLeadPrefix\(family \|\| ""\)\.match\(/);
  assert.match(src, /if \(!normalizedFamily\) return null/);
  assert.match(src, /FROM document_reference_issues dri_family/);
  assert.match(src, /binds: \[`\$\{normalizedFamily\}%`, `ordinance\$\{normalizedFamily\}%`, `%\$\{normalizedFamily\}%`\]/);
  assert.match(src, /const recurringCitationFamilyPrefilter = recurringCitationFamilySqlPrefilter\(options\.recurringCitationFamily\)/);
  assert.match(src, /where\.push\(recurringCitationFamilyPrefilter\.clause\);[\s\S]*binds\.push\(\.\.\.recurringCitationFamilyPrefilter\.binds\)/);
  assert.match(src, /function unresolvedTriageBucketSqlPrefilterClause\(bucket: string \| undefined\)/);
  assert.match(src, /bucket === "unsafe_37x_structural_block"[\s\S]*blocked37xSqlPrefilterClause\(\{ blocked37xOnly: true \} as ListIngestionDocumentsOptions\)/);
  assert.match(src, /bucket === "likely_parenthetical_or_prefix_fix"[\s\S]*FROM document_reference_issues dri_bucket/);
  assert.match(src, /lower\(replace\(COALESCE\(dri_bucket\.raw_value, ''\), ' ', ''\)\) LIKE 'ordinance%\.%'/);
  assert.match(src, /lower\(COALESCE\(dri_bucket\.message, ''\)\) LIKE '%parenthetical%'/);
  assert.match(src, /bucket === "cross_context_ambiguous"[\s\S]*lower\(COALESCE\(dri_bucket\.message, ''\)\) LIKE '%cross%context%'/);
  assert.match(src, /dri_bucket\.reference_type = 'rules_section'[\s\S]*LIKE 'rule37\.%'/);
  assert.match(src, /dri_bucket\.reference_type = 'ordinance_section'[\s\S]*NOT LIKE 'ordinance37\.%'/);
  assert.match(src, /const unresolvedTriageBucketSqlPrefilter = unresolvedTriageBucketSqlPrefilterClause\(options\.unresolvedTriageBucket\)/);
  assert.match(src, /if \(unresolvedTriageBucketSqlPrefilter\) \{\s*where\.push\(unresolvedTriageBucketSqlPrefilter\)/);
  assert.match(src, /function blocked37xSqlPrefilterClause\(options: ListIngestionDocumentsOptions\)/);
  assert.match(src, /function unsafe37xIssueSqlPredicate\(alias: string, families: string\[\] = Array\.from\(UNSAFE_37X\)\)/);
  assert.match(src, /const requireEveryFamily = Boolean\(requestedFamily \|\| requestedBatchFamilies\.length > 0\)/);
  assert.match(src, /const familyGroups = requireEveryFamily \? families\.map\(\(family\) => \[family\]\) : \[families\]/);
  assert.match(src, /unsafe37xIssueSqlPredicate\("dri37", familyGroup\)/);
  assert.match(src, /const blocked37xSqlPrefilter = blocked37xSqlPrefilterClause\(options\)/);
  assert.match(src, /if \(blocked37xSqlPrefilter\) \{\s*where\.push\(blocked37xSqlPrefilter\)/);
  assert.match(src, /if \(options\.safeToBatchReviewOnly\)[\s\S]*dri37_unsafe\.reference_type <> 'ordinance_section'/);
  assert.match(src, /const blockerSqlPrefilter = approvalBlockerSqlPrefilterClause\(options\.blocker\)/);
  assert.match(src, /const requiresDerivedProcessing = usesDerivedListFilter\(options\) \|\| usesDerivedListSort\(options\.sort\)/);
  assert.match(src, /const sqlLimit = requiresDerivedProcessing/);
  assert.match(src, /\.bind\(\.\.\.binds, sqlLimit\)/);
  assert.match(src, /const candidateRows = rows\.results \?\? \[\]/);
  assert.match(src, /const returnedDocuments = filtered\.slice\(0, limit\)/);
  assert.match(src, /const derivedCandidatePoolExhausted = requiresDerivedProcessing && candidateRows\.length >= sqlLimit/);
  assert.match(src, /const derivedCandidatePoolLimited = derivedCandidatePoolExhausted && filtered\.length >= limit/);
  assert.match(src, /documents: returnedDocuments/);
  assert.match(src, /candidatePoolSize: candidateRows\.length/);
  assert.match(src, /derivedProcessingApplied: requiresDerivedProcessing/);
  assert.match(src, /derivedCandidatePoolLimited/);
  assert.doesNotMatch(src, /documents: filtered/);
  assert.match(src, /filtered = filtered\.filter\(\(item\) => item\.approvalReadiness\.eligible\)/);
  assert.match(src, /filtered = filtered\.filter\(\(item\) => item\.reviewerReady\)/);
  assert.match(src, /filtered = filtered\.filter\(\(item\) => \(item\.unresolvedBuckets \|\| \[\]\)\.includes\(options\.unresolvedTriageBucket as string\)\)/);
  assert.match(src, /filtered = filtered\.filter\(\(item\) => \(item\.blocked37xReferences \|\| \[\]\)\.length > 0\)/);
  assert.match(src, /filtered = filtered\.filter\(\(item\) =>\s*\(item\.blocked37xReferences \|\| \[\]\)\.some/);
  assert.match(src, /filtered = filtered\.filter\(\(item\) => item\.blocked37xBatchKey === options\.blocked37xBatchKey\)/);
  assert.match(src, /filtered = filtered\.filter\(\(item\) => item\.blocked37xSafeToBatchReview\)/);
  assert.match(src, /filtered = filtered\.filter\(\(item\) => item\.reviewerRiskLevel === options\.reviewerRiskLevel\)/);
  assert.match(src, /filtered = filtered\.filter\(\(item\) => item\.approvalReadiness\.blockers\.includes\(options\.blocker as string\)\)/);
  assert.match(src, /filtered = filtered\.filter\(\(item\) => item\.runtimeSurfaceForManualReview\)/);
});
