import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";

const searchServicePath = path.resolve(process.cwd(), "src/services/search.ts");
const sharedConceptsPath = path.resolve(process.cwd(), "../../packages/shared/src/search-concepts.ts");
const searchFtsMigrationPath = path.resolve(process.cwd(), "migrations/0008_search_fts.sql");

test("phrase searches use concept coverage instead of isolated substring matches", async () => {
  const src = await fs.readFile(searchServicePath, "utf8");
  const concepts = await fs.readFile(sharedConceptsPath, "utf8");

  assert.match(src, /function phraseConceptVariantsForToken\(token: string\): string\[]/);
  assert.match(src, /conceptVariantsForToken\(normalized, "search"\)/);
  assert.match(concepts, /pattern: \/\^pipes\?\$\//);
  assert.match(concepts, /pattern: \/\^nois\(\?:e\|es\|y\)\$\//);
  assert.match(concepts, /pattern: \/\^roofs\?\$\//);
  assert.match(concepts, /pattern: \/\^ceilings\?\$\//);
  assert.ok(concepts.includes("pattern: /^electrical$|^electric$/"));
  assert.ok(concepts.includes("pattern: /^outlets?$/"));
  assert.ok(concepts.includes("pattern: /^working$/"));
  assert.ok(concepts.includes("pattern: /^rotten$|^rotted$/"));
  assert.ok(concepts.includes("pattern: /^floors?$|^flooring$|^boards?$/"));
  assert.ok(concepts.includes("pattern: /^trash$|^garbage$|^rubbish$|^refuse$/"));
  assert.ok(concepts.includes("pattern: /^odou?rs?$|^smells?$|^smelly$|^stench$/"));
  assert.ok(concepts.includes("pattern: /^drains?$|^drainage$/"));
  assert.ok(concepts.includes("pattern: /^back(?:ing|ed)?$|^backup$|^backups$|^overflow(?:ed|ing)?$/"));
  assert.ok(concepts.includes("pattern: /^hallways?$|^halls?$|^corridors?$/"));
  assert.match(src, /function phraseConceptCoverage\(\s*query: string,\s*text: string,/);
  assert.match(src, /function wholePhraseIndexInNormalizedText\(normalizedText: string, normalizedTerm: string\): number/);
  assert.match(src, /wholePhraseIndexInNormalizedText\(normalizedText, normalizedVariant\)/);
  assert.doesNotMatch(
    src,
    /function phraseConceptCoverage\(\s*query: string,\s*text: string,[\s\S]*normalizedText\.indexOf\(normalizedVariant\)/,
    "Phrase concept coverage should not count substrings inside larger words"
  );
  assert.match(src, /function phraseConceptGuardPasses\(row: ChunkRow, query: string, context\?: SearchContext\): boolean/);
  assert.match(src, /if \(!phraseConceptGuardPasses\(row, query, context\)\) return false/);
  assert.match(src, /phrase_concept_undercoverage_penalty/);
  assert.match(src, /multiword_phrase_match_boost/);
  assert.match(src, /wholePhraseIndexInNormalizedText\(normalizedText, normalizedPhrase\) >= 0\) return 0\.68/);
});

test("phrase execution terms keep SQL scans focused while ranking handles concept expansion", async () => {
  const src = await fs.readFile(searchServicePath, "utf8");

  assert.doesNotMatch(src, /\u0008/, "Search source should not contain literal backspace characters in regexes");
  assert.match(src, /function keywordExecutionTerms\(query: string\): string\[] \{[\s\S]*phraseConceptGroups\(query\)\.length >= 2/);
  assert.match(src, /const tokens = meaningfulLexicalTokens\(query\)\.slice\(0, 4\)/);
  assert.match(src, /return uniq\(\[normalized, \.\.\.tokens\]\.filter\(Boolean\)\)\.slice\(0, 5\)/);
  assert.ok(src.includes("/\\b(?:cockroach|cockroaches|roach|roaches)\\b/"));
  assert.ok(src.includes("/\\b(?:rodent|rodents|rat|rats|mouse|mice)\\b/"));
  assert.doesNotMatch(src, /phrase_concept_scope_fetch/, "Known-slow broad phrase pre-scope should not be in the runtime path");
});

test("phrase searches use FTS before falling back to broad LIKE scans", async () => {
  const src = await fs.readFile(searchServicePath, "utf8");
  const migration = await fs.readFile(searchFtsMigrationPath, "utf8");

  assert.match(migration, /CREATE VIRTUAL TABLE IF NOT EXISTS search_chunks_fts USING fts5/);
  assert.match(migration, /CREATE TRIGGER IF NOT EXISTS document_chunks_ai_search_fts/);
  assert.match(migration, /CREATE TRIGGER IF NOT EXISTS retrieval_search_chunks_ai_search_fts/);
  assert.match(src, /async function ensureSearchFts\(env: Env\): Promise<boolean>/);
  assert.match(src, /function phraseSearchFtsQuery\(query: string\): string/);
  assert.match(src, /async function ftsSearch\(/);
  assert.match(src, /const phraseFtsCandidateSearch =[\s\S]*isPhraseEvidenceQuery\(effectiveQuery\)[\s\S]*!activeStructuredFilterKinds\(parsed\.filters\)\.length/);
  assert.match(src, /: phraseFtsCandidateSearch\s*\?\s*\[\]/);
  assert.match(src, /phraseFtsEligible[\s\S]*await ftsSearch/);
  assert.match(src, /function phraseFtsSearchLimit\(recallConfig: ReturnType<typeof buildAdaptiveRecallConfig>, pageWindow: number\): number/);
  assert.match(src, /const adaptivePhraseFloor = recallConfig\.shortBroadIssueSearch[\s\S]*Math\.max\(pageWindow \* 6, 120\)/);
  assert.match(src, /phraseFtsSearchLimit\(recallConfig, pageWindow\)/);
  assert.doesNotMatch(src, /Math\.max\(recallConfig\.lexicalSearchLimit, 360\)/);
  assert.match(src, /const phraseFtsHasEnoughEvidence =[\s\S]*phraseFtsEligible[\s\S]*lexicalRows\.length >= Math\.min\(Math\.max\(parsed\.limit, 8\), 18\)/);
  assert.match(src, /shouldSkipVectorSearch\(effectiveQuery, parsed\.filters, queryType\) \|\| phraseFtsHasEnoughEvidence/);
  assert.match(src, /if \(!skipLexicalForVectorFirstIssueSearch && lexicalRows\.length === 0\)[\s\S]*await lexicalSearch/);
});

test("phrase snippets prefer phrase evidence and avoid common drift cases", async () => {
  const src = await fs.readFile(searchServicePath, "utf8");

  assert.match(src, /const authorityPhraseCoverage = authoritySnippet\s*\? phraseConceptCoverage/);
  assert.match(src, /const factPhraseCoverage = factSnippet\s*\? phraseConceptCoverage/);
  assert.match(src, /factPhraseCoverage\.matchedCount > authorityPhraseCoverage\.matchedCount/);
  assert.match(src, /function hasWaterHeaterDrift\(query: string, text: string, precomputed\?: \{ normalizedQuery\?: string; normalizedText\?: string \}\): boolean/);
  assert.match(src, /room_heat_water_heater_drift_penalty/);
  assert.match(src, /function hasCapitalImprovementCostDrift\(query: string, text: string, precomputed\?: \{ normalizedQuery\?: string; normalizedText\?: string \}\): boolean/);
  assert.match(src, /phrase_capital_improvement_cost_drift_penalty/);
  assert.match(src, /function hasLeakWindowContext\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /function leakWindowContextAdjustment\([\s\S]*precomputed\?: \{ normalizedQuery\?: string; normalizedText\?: string \}[\s\S]*\): \{ score: number; reason: string \| null \}/);
  assert.match(src, /leak_window_split_evidence_penalty/);
  assert.match(src, /leak_window_bathroom_context_boost/);
  assert.match(src, /leak_window_missing_bathroom_penalty/);
  assert.match(src, /phraseFtsSearchLimit\(recallConfig, pageWindow\)/);
  assert.match(src, /function hasConcretePhraseFactSignal\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /function isGenericHousingServiceStandard\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /phrase_exact_fact_evidence_boost/);
  assert.match(src, /document_phrase_exact_fact_boost/);
  assert.match(src, /decision_layer_exact_phrase_evidence_boost/);
  assert.match(src, /isPhraseEvidenceQuery\(effectiveQuery\)[\s\S]*Math\.min\(0\.04, Math\.max\(0, docHitCount - 1\) \* 0\.01\)/);
  assert.match(src, /queryDerived\.phraseEvidenceQuery[\s\S]*Math\.min\(0\.04, Math\.max\(0, docHitCount - 1\) \* 0\.01\)/);
  assert.match(src, /phrase_generic_legal_standard_penalty/);
});

test("search scoring uses per-search derived query context in hot row scoring", async () => {
  const src = await fs.readFile(searchServicePath, "utf8");

  assert.match(src, /interface QueryDerivedContext/);
  assert.match(src, /function buildQueryDerivedContext\(context: SearchContext\): QueryDerivedContext/);
  assert.match(src, /function getQueryDerivedContext\(context: SearchContext\): QueryDerivedContext/);
  assert.match(src, /context\.derived = buildQueryDerivedContext\(context\)/);
  assert.match(src, /rowSearchableTextCache\?: Map<string, string>/);
  assert.match(src, /normalizedRowSearchableTextCache\?: Map<string, string>/);
  assert.match(src, /normalizedRowChunkTextCache\?: Map<string, string>/);
  assert.match(src, /rowMetadataCache\?: Map<string, RowMetadata>/);
  assert.match(src, /function cachedCombinedSearchableText\(row: ChunkRow, context: SearchContext\): string/);
  assert.match(src, /function cachedNormalizedSearchableText\(row: ChunkRow, context: SearchContext\): string/);
  assert.match(src, /function cachedNormalizedChunkText\(row: ChunkRow, context: SearchContext\): string/);
  assert.match(src, /interface RowMetadata \{[\s\S]*normalizedIndexCodes: string\[\]/);
  assert.match(src, /interface RowMetadata \{[\s\S]*normalizedTitle: string;[\s\S]*normalizedCitation: string;/);
  assert.match(src, /function cachedRowMetadata\(row: ChunkRow, context: SearchContext\): RowMetadata/);
  assert.match(src, /normalizedTitle: normalize\(row\.title\)/);
  assert.match(src, /normalizedCitation: normalize\(row\.citation\)/);
  assert.match(src, /precomputed\?: \{ normalizedQuery\?: string; normalizedGroups\?: string\[\]\[\]; normalizedText\?: string \}/);
  assert.match(src, /const normalizedText = precomputed\?\.normalizedText \?\? normalize\(text \|\| ""\)/);
  assert.match(src, /function rowHasLiteralKeywordMatch\(row: ChunkRow, query: string, context\?: SearchContext\): boolean/);
  assert.match(src, /function phraseConceptGuardPasses\(row: ChunkRow, query: string, context\?: SearchContext\): boolean/);
  assert.match(src, /function rowMatchesQueryGuard\(row: ChunkRow, query: string, context\?: SearchContext\): boolean/);
  assert.match(src, /const queryDerived = getQueryDerivedContext\(context\)/);
  assert.match(src, /normalizedIssueTerms: issueTerms\.map\(\(term\) => normalize\(term\)\)\.filter\(Boolean\)/);
  assert.match(src, /normalizedProceduralTerms: proceduralTerms\.map\(\(term\) => normalize\(term\)\)\.filter\(Boolean\)/);
  assert.match(src, /longQueryTokens: tokenize\(context\.query\)\.filter\(\(token\) => token\.length > 3\)/);
  assert.match(src, /normalizedPrimarySignals: primarySignals\.map\(\(signal\) => normalize\(signal\)\)/);
  assert.match(src, /\.\.\.queryDerived\.longQueryTokens/);
  assert.match(src, /const issueTerms = queryDerived\.normalizedIssueTerms/);
  assert.match(src, /precomputed\?: \{ normalizedText\?: string; normalizedSignal\?: string \}/);
  assert.match(src, /const normalizedText = precomputed\?\.normalizedText \?\? normalize\(text\)/);
  assert.match(src, /function hasOwnerMoveInPhrase\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /function hasWrongfulEvictionPhrase\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /hasOwnerMoveInPhrase\(normalizedText, \{ normalizedText \}\)/);
  assert.match(src, /hasOwnerMoveInPhrase\(normalized, \{ normalizedText: normalized \}\)/);
  assert.match(src, /hasWrongfulEvictionPhrase\(normalized, \{ normalizedText: normalized \}\)/);
  assert.match(src, /containsWholeWord\(normalized, "awe", \{ normalizedText: normalized \}\)/);
  assert.match(src, /const normalizedText = \{ normalizedText: normalized \}/);
  assert.match(src, /hasOwnerMoveInPhrase\(normalized, normalizedText\)/);
  assert.match(src, /hasWrongfulEvictionPhrase\(normalized, normalizedText\)/);
  assert.match(src, /const normalizedPrimarySignals = queryDerived\.normalizedPrimarySignals/);
  assert.match(src, /function issueSignalHitCount\(text: string, signals: string\[\], precomputed\?: \{ normalizedText\?: string; normalizedSignals\?: string\[\] \}\): number/);
  assert.match(src, /normalizedSignal: precomputed\?\.normalizedSignals\?\.\[index\]/);
  assert.match(src, /issueSignalHitCount\(loweredSnippet, primarySignals,[\s\S]*normalizedText: loweredSnippet,[\s\S]*normalizedSignals: normalizedPrimarySignals/);
  assert.match(src, /const normalizedQueryContext = \{ normalizedQuery \}/);
  assert.match(src, /const referencedJudges = queryDerived\.referencedJudges/);
  assert.match(src, /function isPhraseEvidenceQuery\(query: string, precomputed\?: \{ normalizedGroups\?: string\[\]\[\] \}\): boolean/);
  assert.match(src, /phraseEvidenceQuery: isPhraseEvidenceQuery\(context\.query, \{ normalizedGroups: normalizedPhraseConceptGroups \}\)/);
  assert.match(src, /queryDerived\.phraseEvidenceQuery/);
  assert.match(src, /literalKeywordQuery: isLiteralKeywordQuery\(context\.query\)/);
  assert.match(src, /if \(queryDerived\.literalKeywordQuery\) \{/);
  assert.match(src, /leakWindowQuery: isLeakWindowQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /if \(queryDerived\.leakWindowQuery\) \{/);
  assert.match(src, /ownerMoveInFollowThroughRequired: requiresOwnerMoveInFollowThroughSpecificity\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /habitabilityServiceQuery: hasHabitabilityServiceRestorationSignals\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /requiredHabitabilitySignals: requiredHabitabilityPrimarySignals\(context\.query\)/);
  assert.match(src, /lockoutSpecificityRequired: requiresLockoutSpecificity\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /lockBoxQuery: isLockBoxQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /harassmentRetaliationQuery: \/\\bharassment\|retaliation\\b\/\.test\(normalizedQuery\)/);
  assert.match(src, /wrongfulEvictionQuery: hasWrongfulEvictionPhrase\(normalizedQuery, \{ normalizedText: normalizedQuery \}\)/);
  assert.match(src, /wrongfulEvictionIssueQuery: isWrongfulEvictionIssueSearch\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /coolingIssueQuery: isCoolingIssueQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /conditionIssueQuery: isConditionIssueQuery\(context\.query\)/);
  assert.match(src, /noticeProceduralQuery: isNoticeProceduralQuery\(context\.query\)/);
  assert.match(src, /strongIssueEvidenceRequired: requiresStrongIssueEvidence\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /accommodationQuery: isAccommodationQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /homeownersExemptionQuery: isHomeownersExemptionQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /selfEmployedQuery: isSelfEmployedQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /adjudicatedQuery: isAdjudicatedQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /socialMediaQuery: isSocialMediaQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /caregiverQuery: isCaregiverQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /mootQuery: isMootQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /divorceQuery: isDivorceQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /remoteWorkQuery: isRemoteWorkQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /collegeQuery: isCollegeQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /coLivingQuery: isCoLivingQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /buyoutQuery: isBuyoutQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /buyoutPressureQuery: isBuyoutPressureQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /evictionProtectionQuery: isEvictionProtectionQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /packageSecurityQuery: isPackageSecurityQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /cameraPrivacyQuery: isCameraPrivacyQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /poopQuery: isPoopQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /dogQuery: isDogQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /intercomQuery: isIntercomQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /garageSpaceQuery: isGarageSpaceQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /commonAreasQuery: isCommonAreasQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /stairsQuery: isStairsQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /porchQuery: isPorchQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /windowsQuery: isWindowsQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /section8Query: isSection8Query\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /unlawfulDetainerQuery: isUnlawfulDetainerQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /roomHeatQuery: isRoomHeatQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /queryMentionsMold: containsWholeWord\(context\.query, "mold", \{ normalizedText: normalizedQuery \}\)/);
  assert.match(src, /queryMentionsMildew: containsWholeWord\(context\.query, "mildew", \{ normalizedText: normalizedQuery \}\)/);
  assert.match(src, /normalizedSentenceIssueAnchors: sentenceIssueAnchors\.map\(\(term\) => normalize\(term\)\)/);
  assert.match(src, /normalizedSentenceSecondaryTokens: sentenceSecondaryTokens\.map\(\(term\) => normalize\(term\)\)/);
  assert.match(src, /normalizedSentenceFactualTokens = uniq\(\[\.\.\.sentenceIssueAnchors, \.\.\.sentenceSecondaryTokens\]\)/);
  assert.match(src, /precomputedFactualTokens \?\?/);
  assert.match(src, /const normalizedText = precomputed\?\.normalizedText \?\? normalize\(text \|\| ""\)/);
  assert.match(src, /sentenceFactualTokenMetrics\(context\.query, searchableText, queryDerived\.normalizedSentenceFactualTokens,[\s\S]*normalizedText: loweredSnippet/);
  assert.match(src, /normalizedPhraseConceptGroups = phraseConceptGroups\(context\.query\)\.map/);
  assert.match(src, /precomputed\?\.normalizedGroups \?\?/);
  assert.match(src, /phraseConceptCoverage\(context\.query, searchableText,[\s\S]*queryDerived\.normalizedPhraseConceptGroups/);
  assert.match(src, /function exactMultiWordPhraseScore\(query: string, text: string, precomputed\?: \{ normalizedText\?: string \}\): number/);
  assert.match(src, /const normalizedCoverageText = precomputed\?\.normalizedText \?\? normalize\(text\)/);
  assert.match(src, /exactMultiWordPhraseScore\(context\.query, searchableText, \{ normalizedText: loweredSnippet \}\)/);
  assert.match(src, /const aggregatedText = candidates\.map\(\(candidate\) => cachedNormalizedSearchableText\(candidate\.row, context\)\)\.join\(" "\)/);
  assert.match(src, /function buildDocumentEvidenceSummary[\s\S]*sentenceFactualTokenMetrics\(context\.query, searchableText, queryDerived\.normalizedSentenceFactualTokens,[\s\S]*normalizedText/);
  assert.match(src, /function buildDocumentEvidenceSummary[\s\S]*issueSignalHitCount\(aggregatedText, primarySignals,[\s\S]*normalizedSignals: queryDerived\.normalizedPrimarySignals/);
  assert.match(src, /function buildDocumentEvidenceSummary[\s\S]*issueSignalHitCount\(normalizedText, primarySignals,[\s\S]*normalizedSignals: queryDerived\.normalizedPrimarySignals/);
  assert.match(src, /function representativeChunkDisplayScore[\s\S]*sentenceFactualTokenMetrics\(context\.query, searchableText, queryDerived\.normalizedSentenceFactualTokens,[\s\S]*exactMultiWordPhraseScore\(context\.query, searchableText, \{ normalizedText \}\)/);
  assert.match(src, /function representativeChunkDisplayScore[\s\S]*issueSignalHitCount\(normalizedText, primarySignals,[\s\S]*normalizedSignals: queryDerived\.normalizedPrimarySignals/);
  assert.match(src, /function authorityPassageScore[\s\S]*sentenceFactualTokenMetrics\(context\.query, searchableText, queryDerived\.normalizedSentenceFactualTokens,[\s\S]*exactMultiWordPhraseScore\(context\.query, searchableText, \{ normalizedText \}\)/);
  assert.match(src, /function authorityPassageScore[\s\S]*issueSignalHitCount\(normalizedText, queryDerived\.primarySignals,[\s\S]*normalizedSignals: queryDerived\.normalizedPrimarySignals/);
  assert.match(src, /function supportingFactAnchorDiagnostics[\s\S]*sentenceFactualTokenMetrics\(context\.query, searchableText, queryDerived\.normalizedSentenceFactualTokens,[\s\S]*normalizedText/);
  assert.match(src, /function supportingFactAnchorDiagnostics[\s\S]*issueSignalHitCount\(normalizedText, primarySignals,[\s\S]*normalizedSignals: queryDerived\.normalizedPrimarySignals/);
  assert.match(src, /const habitabilityServiceQuery = queryDerived\.habitabilityServiceQuery/);
  assert.match(src, /const lockoutSpecificityRequired = queryDerived\.lockoutSpecificityRequired/);
  assert.match(src, /const requiredConditionSignals = queryDerived\.requiredHabitabilitySignals/);
  assert.match(src, /function fetchSupportingFactChunksByDocumentIds[\s\S]*const normalizedText = cachedNormalizedChunkText\(row, context\)/);
  assert.match(src, /const searchableText = cachedCombinedSearchableText\(row, context\)/);
  assert.match(src, /const loweredSnippet = cachedNormalizedSearchableText\(row, context\)/);
  assert.match(src, /const normalizedTextContext = \{ normalizedQuery: queryDerived\.normalizedQuery, normalizedText: loweredSnippet \}/);
  assert.match(src, /hasAccommodationContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasSection8Context\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasUnlawfulDetainerContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasOwnerMoveInContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasOwnerMoveInFollowThroughContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasEmploymentAccommodationDrift\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasLockBoxContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasHomeownersExemptionContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCameraPrivacyContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasPackageDeliverySecurityContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasPackageSecurityContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasDogPolicyContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasDogParkContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasDogContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCollegeContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasSelfEmployedContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasAdjudicatedContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasSocialMediaContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCaregiverContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasPoopContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasMootContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasRemoteWorkContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasDivorceContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasIntercomContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasGarageSpaceContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCommonAreasContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasStairsContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasPorchContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasWindowsContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCoLivingContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasBuyoutPressureContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasBuyoutContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasSection8RehabDrift\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasSection827RentIncreaseDrift\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasWrongfulEvictionLockoutContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasWrongfulEvictionContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasHarassmentContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasRepairNoticeContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /isHousingServicesDefinitionBoilerplate\(searchableText, normalizedTextContext\)/);
  assert.match(src, /isOwnerMoveInLegalStandardBoilerplate\(searchableText, normalizedTextContext\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*hasSection8Context\(searchableText, \{ normalizedText \}\)[\s\S]*hasBuyoutContext\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /function buildSection8UdDocumentSupportSet[\s\S]*const normalizedText = context \? cachedNormalizedSearchableText\(row, context\) : normalize\(searchableText\)[\s\S]*hasUnlawfulDetainerContext\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /function isPackageSecurityQuery\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): boolean/);
  assert.match(src, /function isSection8UnlawfulDetainerQuery\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): boolean/);
  assert.match(src, /function isEvictionProtectionQuery\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): boolean/);
  assert.match(src, /function hasWrongContextForQuery\(query: string, text: string, precomputed\?: \{ normalizedQuery\?: string; normalizedText\?: string \}\)/);
  assert.match(src, /function hasWrongContextForQuery[\s\S]*const normalizedQuery = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)/);
  assert.match(src, /function hasWrongContextForQuery[\s\S]*const normalizedQueryContext = \{ normalizedQuery \}/);
  assert.match(src, /function hasWrongContextForQuery[\s\S]*isPackageSecurityQuery\(query, normalizedQueryContext\)/);
  assert.match(src, /hasWrongContextForQuery\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /function buildIssueFamilyFallbackCandidates[\s\S]*return !hasWrongContextForQuery\(context\.query, searchableText, \{ normalizedQuery: queryDerived\.normalizedQuery, normalizedText \}\)/);
  assert.match(src, /function buildIssueFamilyFallbackCandidates[\s\S]*!hasSection8Context\(searchableText, \{ normalizedText \}\)[\s\S]*!hasUnlawfulDetainerContext\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /const issueFamilyDecisionScopeSeedIds[\s\S]*hasHomeownersExemptionContext\(searchableText, \{ normalizedText \}\)[\s\S]*hasCoLivingContext\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /queryDerived\.lockBoxQuery/);
  assert.match(src, /queryDerived\.accommodationQuery/);
  assert.match(src, /queryDerived\.homeownersExemptionQuery/);
  assert.match(src, /queryDerived\.selfEmployedQuery/);
  assert.match(src, /queryDerived\.adjudicatedQuery/);
  assert.match(src, /queryDerived\.socialMediaQuery/);
  assert.match(src, /queryDerived\.caregiverQuery/);
  assert.match(src, /queryDerived\.mootQuery/);
  assert.match(src, /queryDerived\.divorceQuery/);
  assert.match(src, /queryDerived\.remoteWorkQuery/);
  assert.match(src, /queryDerived\.collegeQuery/);
  assert.match(src, /queryDerived\.coLivingQuery/);
  assert.match(src, /queryDerived\.buyoutQuery/);
  assert.match(src, /queryDerived\.packageSecurityQuery/);
  assert.match(src, /queryDerived\.cameraPrivacyQuery/);
  assert.match(src, /queryDerived\.poopQuery/);
  assert.match(src, /queryDerived\.dogQuery/);
  assert.match(src, /queryDerived\.roomHeatQuery/);
  assert.match(src, /const rowReferencedJudgeMatch = queryDerived\.judgeDrivenQuery/);
  assert.match(src, /const rowMetadata = cachedRowMetadata\(row, context\)/);
  assert.match(src, /const normCitation = rowMetadata\.normalizedCitation/);
  assert.match(src, /const indexCodes = rowMetadata\.normalizedIndexCodes/);
  assert.match(src, /const ruleSections = rowMetadata\.normalizedRulesSections/);
  assert.match(src, /const ordinanceSections = rowMetadata\.normalizedOrdinanceSections/);
  assert.match(src, /rowMetadata\.normalizedTitle\.includes\(queryDerived\.normalizedPartyNameFilter\)/);
  assert.match(src, /normalizedIndexCodeRelatedRulesSections: indexCodeFilterContext\.relatedRulesSections\.map\(\(item\) => normalize\(item\)\)\.filter\(Boolean\)/);
  assert.match(src, /normalizedIndexCodeRelatedOrdinanceSections: indexCodeFilterContext\.relatedOrdinanceSections\.map\(\(item\) => normalize\(item\)\)\.filter\(Boolean\)/);
  assert.match(src, /normalizedIndexCodeSearchPhrases: indexCodeFilterContext\.searchPhrases\.map\(\(item\) => normalize\(item\)\)\.filter\(Boolean\)/);
  assert.match(src, /queryDerived\.normalizedIndexCodeRelatedRulesSections\.some/);
  assert.match(src, /queryDerived\.normalizedIndexCodeRelatedOrdinanceSections\.some/);
  assert.match(src, /queryDerived\.normalizedIndexCodeSearchPhrases\.some/);
  assert.doesNotMatch(src, /if \(isDogQuery\(context\.query\)\)/);
  assert.doesNotMatch(src, /if \(isRoomHeatQuery\(context\.query\) &&/);
  assert.match(src, /const sentenceIssueAnchors = queryDerived\.normalizedSentenceIssueAnchors/);
  assert.match(src, /const sentenceSecondaryTokens = queryDerived\.normalizedSentenceSecondaryTokens/);
  assert.match(src, /const normalizedMildewText = loweredSnippet/);
  assert.match(src, /const normalizedPoopText = loweredSnippet/);
  assert.match(src, /socialSecurityDrift =\s*\/\\bsocial security\\b[\s\S]*\.test\(loweredSnippet\)/);
  assert.match(src, /camera_privacy_missing_camera_penalty/);
  assert.match(src, /package_security_sensitive_drift_penalty/);
  assert.match(src, /collegeBondDrift =\s*\/\\bcommunity college district\\b[\s\S]*\.test\(\s*loweredSnippet\s*\)/);
  assert.match(src, /remote_work_partial_phrase_boost/);
  assert.match(src, /windows_capital_improvement_drift_penalty/);
  assert.match(src, /buyout_pressure_generic_settlement_penalty/);
  assert.match(src, /const normalizedAuthoritySnippet = normalize\(authoritySnippet\)/);
  assert.match(src, /const normalizedFactSnippet = normalize\(factSnippet\)/);
  assert.match(src, /phraseConceptCoverage\(context\.query, authoritySnippet, \{ \.\.\.phraseConceptContext, normalizedText: normalizedAuthoritySnippet \}\)/);
  assert.match(src, /phraseConceptCoverage\(context\.query, factSnippet, \{ \.\.\.phraseConceptContext, normalizedText: normalizedFactSnippet \}\)/);
  assert.match(src, /const sentenceStyle = queryDerived\.sentenceStyleReasoningQuery/);
  assert.match(src, /const phraseEvidenceQuery = queryDerived\.phraseEvidenceQuery/);
  assert.match(src, /const requiredMatches = 2/);
  assert.match(src, /function phraseConceptGuardPasses[\s\S]*normalizedText: cachedNormalizedSearchableText\(row, context\)/);
  assert.match(src, /function scoreRow[\s\S]*normalizedText: loweredSnippet/);
  assert.match(src, /function lexicalScore[\s\S]*phraseConceptCoverage\(query, text, \{ normalizedText: lower \}\)/);
  assert.match(src, /function buildDocumentEvidenceSummary[\s\S]*normalizedText: aggregatedText/);
  assert.match(src, /function buildDocumentEvidenceSummary[\s\S]*phraseConceptCoverage\(context\.query, searchableText, \{ \.\.\.phraseConceptContext, normalizedText \}\)/);
  assert.match(src, /function representativeChunkDisplayScore[\s\S]*const queryDerived = getQueryDerivedContext\(context\)/);
  assert.match(src, /function representativeChunkDisplayScore[\s\S]*cachedNormalizedSearchableText\(candidate\.row, context\)/);
  assert.match(src, /function authorityPassageScore[\s\S]*const queryDerived = getQueryDerivedContext\(context\)/);
  assert.match(src, /function authorityPassageScore[\s\S]*cachedNormalizedSearchableText\(candidate\.row, context\)/);
  assert.match(src, /function authorityPassageScore[\s\S]*normalizedText\s*\n\s*\}\)/);
  assert.match(src, /function supportingFactAnchorDiagnostics[\s\S]*const queryDerived = getQueryDerivedContext\(context\)/);
  assert.match(src, /function supportingFactAnchorDiagnostics[\s\S]*cachedNormalizedSearchableText\(candidate\.row, context\)/);
  assert.match(src, /function supportingFactAnchorDiagnostics[\s\S]*normalizedText\s*\n\s*\}\)/);
  assert.match(src, /function pickSupportingFactCandidate[\s\S]*cachedCombinedSearchableText\(item\.candidate\.row, context\)/);
  assert.match(src, /function pickSupportingFactCandidate[\s\S]*cachedNormalizedSearchableText\(item\.candidate\.row, context\)/);
  assert.match(src, /function buildDecisionScopedCandidates[\s\S]*const queryDerived = getQueryDerivedContext\(context\)/);
  assert.match(src, /rowMatchesQueryGuard\(row, context\.query, context\)/);
  assert.match(src, /rowMatchesQueryGuard\(row, effectiveQuery, context\)/);
  assert.match(src, /function rowMatchesQueryGuard\(row: ChunkRow, query: string, context\?: SearchContext\): boolean[\s\S]*const normalizedText = context \? cachedNormalizedSearchableText\(row, context\) : normalize\(searchableText\)/);
  assert.match(src, /function rowMatchesQueryGuard[\s\S]*hasHomeownersExemptionContext\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /function containsWholeWord\(text: string, term: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /function buildDecisionScopedCandidates[\s\S]*cachedCombinedSearchableText\(row, context\)/);
  assert.match(src, /const issueFamilyDecisionScopeSeedIds =[\s\S]*cachedCombinedSearchableText\(row, context\)/);
  assert.match(src, /function chunkMatchesIssueTerms\(row: ChunkRow, query: string, context\?: SearchContext\): boolean/);
  assert.match(src, /context \? cachedNormalizedSearchableText\(row, context\) : normalize\(combinedSearchableText\(row\)\)/);
  assert.match(src, /function hasStrongIssueEvidence\([\s\S]*context\?: SearchContext[\s\S]*cachedCombinedSearchableText\(row, context\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*const normalizedQuery = context \? getQueryDerivedContext\(context\)\.normalizedQuery : normalize\(query \|\| ""\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*const normalizedQueryContext = \{ normalizedText: normalizedQuery \}/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*containsWholeWord\(searchableText, query, \{ normalizedText \}\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*hasOwnerMoveInPhrase\(normalizedQuery, normalizedQueryContext\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*containsWholeWord\(normalizedQuery, "omi", normalizedQueryContext\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*hasWrongfulEvictionPhrase\(normalizedQuery, normalizedQueryContext\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*containsWholeWord\(normalizedQuery, "awe", normalizedQueryContext\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*containsWholeWord\(searchableText, "owner occupancy", \{ normalizedText \}\)/);
  assert.match(src, /function hasPetPolicyDrift\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /function hasCoolingProxyDrift\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /function isCapitalImprovementBoilerplate\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /function hasMoldCollision\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /hasMoldCollision\(searchableText, normalizedTextContext\)/);
  assert.match(src, /function hasLeakWindowContext\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /function hasBathroomWindowContext\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /function isLeakWindowQuery\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): boolean/);
  assert.match(src, /function leakWindowContextAdjustment\([\s\S]*precomputed\?: \{ normalizedQuery\?: string; normalizedText\?: string \}/);
  assert.match(src, /leakWindowContextAdjustment\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /function hasHeatApplianceDrift\(query: string, text: string, precomputed\?: \{ normalizedQuery\?: string; normalizedText\?: string \}\): boolean/);
  assert.match(src, /hasHeatApplianceDrift\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /hasWaterHeaterDrift\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCapitalImprovementCostDrift\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /const normalizedTextContext = \{ normalizedQuery: queryDerived\.normalizedQuery, normalizedText \}/);
  assert.match(src, /hasWaterHeaterDrift\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCapitalImprovementCostDrift\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /leakWindowContextAdjustment\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /function habitabilityCoverageSignals\(text: string, query: string, precomputed\?: \{ normalizedText\?: string \}\)/);
  assert.match(src, /const combinedHabitabilityText = `\$\{authorityText\} \$\{supportText\}`\.trim\(\)/);
  assert.match(src, /habitabilityCoverageSignals\(authorityText, context\.query, \{ normalizedText: authorityText \}\)/);
  assert.match(src, /habitabilityCoverageSignals\(combinedHabitabilityText, context\.query, \{ normalizedText: combinedHabitabilityText \}\)/);
  assert.match(src, /function hasStrongPoopDecisionContext\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /function hasWeakRodentPoopContext\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /const combinedPoopLayerText = `\$\{authorityText\} \$\{supportText\}`\.trim\(\)/);
  assert.match(src, /hasStrongPoopDecisionContext\(combinedPoopLayerText, \{ normalizedText: combinedPoopLayerText \}\)/);
  assert.match(src, /hasWeakRodentPoopContext\(layerText, \{ normalizedText: layerText \}\)/);
  assert.match(src, /const layerNormalizedTextContext = \{ normalizedQuery: queryDerived\.normalizedQuery, normalizedText: layerText \}/);
  assert.match(src, /const layerLeakWindowAdjustment = leakWindowContextAdjustment\(context\.query, layerText, layerNormalizedTextContext\)/);
  assert.match(src, /function hasConcretePhraseFactSignal\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /function isGenericHousingServiceStandard\(text: string, precomputed\?: \{ normalizedText\?: string \}\): boolean/);
  assert.match(src, /hasConcretePhraseFactSignal\(searchableText, normalizedTextContext\)/);
  assert.match(src, /isGenericHousingServiceStandard\(searchableText, normalizedTextContext\)/);
  assert.match(src, /const aggregateConcretePhraseFacts = hasConcretePhraseFactSignal\(aggregatedText, \{ normalizedText: aggregatedText \}\)/);
  assert.match(src, /hasConcretePhraseFactSignal\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /function hasWrongContextForQuery[\s\S]*hasPetPolicyDrift\(normalizedText, \{ normalizedText \}\)[\s\S]*isCapitalImprovementBoilerplate\(normalizedText, \{ normalizedText \}\)/);
  assert.match(src, /isCapitalImprovementBoilerplate\(row\.chunkText, \{ normalizedText: cachedNormalizedChunkText\(row, context\) \}\)/);
  assert.match(src, /function buildSection8UdDocumentSupportSet\(rows: ChunkRow\[], context\?: SearchContext\): Set<string>/);
  assert.match(src, /function chunkQualifiesForSection8UdDocumentSupport\([\s\S]*context\?: SearchContext[\s\S]*chunkMatchesSection8UdDocumentSupport\(row, section8UdDocumentSupportIds, context\)/);
  assert.match(src, /hasStrongIssueEvidence\(context\.query, row, issueTermHits, proceduralTermHits, context\)/);
  assert.match(src, /buildSection8UdDocumentSupportSet\(rows, context\)/);
  assert.match(src, /chunkQualifiesForSection8UdDocumentSupport\(row, diagnostics, section8UdDocumentSupportIds, context\)/);
  assert.match(src, /chunkMatchesIssueTerms\(row, context\.query, context\)/);
  assert.match(src, /chunkMatchesProceduralTerms\(row, context\.query, context\)/);
  assert.match(src, /const issueHits = queryDerived\.normalizedIssueTerms\.filter/);
  assert.match(src, /const proceduralHits = queryDerived\.normalizedProceduralTerms\.filter/);
});
