import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";

const searchServicePath = path.resolve(process.cwd(), "src/services/search.ts");
const sharedConceptsPath = path.resolve(process.cwd(), "../../packages/shared/src/search-concepts.ts");
const searchFtsMigrationPath = path.resolve(process.cwd(), "migrations/0008_search_fts.sql");

test("phrase searches use concept coverage instead of isolated substring matches", async () => {
  const src = (await Promise.all((await fs.readdir(path.resolve(process.cwd(), "src/services"))).filter((f) => /^search.*\.ts$/.test(f)).sort().map((f) => fs.readFile(path.resolve(process.cwd(), "src/services", f), "utf8")))).join("\n").replace(/^export /gm, "");
  const searchClassificationSrc = await fs.readFile(path.resolve(process.cwd(), "src/services/search-query-classification.ts"), "utf8");
  const searchConceptsSrc = await fs.readFile(path.resolve(process.cwd(), "src/services/search-concepts.ts"), "utf8");
  const concepts = await fs.readFile(sharedConceptsPath, "utf8");

  assert.match(searchConceptsSrc, /conceptVariantsForToken\(normalized, "search"\)/);
  assert.match(concepts, /pattern: \/\^pipes\?\$\//);
  assert.match(concepts, /pattern: \/\^nois\(\?:e\|es\|y\)\$\//);
  assert.match(concepts, /pattern: \/\^roofs\?\$\//);
  assert.match(concepts, /pattern: \/\^ceilings\?\$\//);
  assert.ok(concepts.includes("pattern: /^electrical$|^electric$/"));
  assert.ok(concepts.includes("pattern: /^outlets?$/"));
  assert.ok(concepts.includes("pattern: /^working$/"));
  assert.ok(concepts.includes("pattern: /^rotten$|^rotted$/"));
  assert.ok(concepts.includes("pattern: /^floors?$|^flooring$|^boards?$/"));
  assert.ok(concepts.includes("pattern: /^trash$|^garbage$|^rubbish$|^refuse$/"));
  assert.ok(concepts.includes("pattern: /^odou?rs?$|^smells?$|^smelly$|^stench$/"));
  assert.ok(concepts.includes("pattern: /^drains?$|^drainage$/"));
  assert.ok(concepts.includes("pattern: /^back(?:ing|ed)?$|^backup$|^backups$|^overflow(?:ed|ing)?$/"));
  assert.ok(concepts.includes("pattern: /^hallways?$|^halls?$|^corridors?$/"));
  assert.match(searchConceptsSrc, /wholePhraseIndexInNormalizedText\(normalizedText, normalizedVariant\)/);
  assert.doesNotMatch(
    searchConceptsSrc,
    /function phraseConceptCoverage\(\s*query: string,\s*text: string,[\s\S]*normalizedText\.indexOf\(normalizedVariant\)/,
    "Phrase concept coverage should not count substrings inside larger words"
  );
  assert.match(searchClassificationSrc, /function shouldUsePhraseConceptGuard\(query: string, precomputed\?: \{ normalizedGroups\?: string\[\]\[\]; normalizedQuery\?: string \}\): boolean \{\s*const groups = precomputed\?\.normalizedGroups \?\? phraseConceptGroups\(query\)/);
  assert.match(src, /function phraseConceptGuardPasses\(row: ChunkRow, query: string, context: SearchContext\): boolean[\s\S]*const queryDerived = getQueryDerivedContext\(context\)[\s\S]*normalizedGroups: queryDerived\.normalizedPhraseConceptGroups,[\s\S]*normalizedQuery: queryDerived\.normalizedQuery[\s\S]*shouldUsePhraseConceptGuard\(query, phraseConceptContext\)/);
  assert.match(src, /if \(!phraseConceptGuardPasses\(row, query, context\)\) return false/);
  assert.match(src, /phrase_concept_undercoverage_penalty/);
  assert.match(src, /multiword_phrase_match_boost/);
  assert.match(src, /wholePhraseIndexInNormalizedText\(normalizedText, normalizedPhrase\) >= 0\) return 0\.68/);
});

test("phrase execution terms keep SQL scans focused while ranking handles concept expansion", async () => {
  const src = (await Promise.all((await fs.readdir(path.resolve(process.cwd(), "src/services"))).filter((f) => /^search.*\.ts$/.test(f)).sort().map((f) => fs.readFile(path.resolve(process.cwd(), "src/services", f), "utf8")))).join("\n").replace(/^export /gm, "");

  assert.doesNotMatch(src, /\u0008/, "Search source should not contain literal backspace characters in regexes");
  assert.match(src, /function keywordExecutionTerms\(query: string, precomputed\?: \{ normalizedQuery\?: string; normalizedGroups\?: string\[\]\[\] \}\): string\[\] \{[\s\S]*const normalizedGroups = precomputed\?\.normalizedGroups \?\? phraseConceptGroups\(normalizedQuery\)[\s\S]*if \(normalizedGroups\.length >= 2\)/);
  assert.match(src, /const tokens = meaningfulLexicalTokens\(normalizedQuery\)\.slice\(0, 4\)/);
  assert.match(src, /return uniq\(\[normalized, \.\.\.tokens\]\.filter\(Boolean\)\)\.slice\(0, 5\)/);
  assert.ok(src.includes("/\\b(?:cockroach|cockroaches|roach|roaches)\\b/"));
  assert.ok(src.includes("/\\b(?:rodent|rodents|rat|rats|mouse|mice)\\b/"));
  assert.doesNotMatch(src, /phrase_concept_scope_fetch/, "Known-slow broad phrase pre-scope should not be in the runtime path");
});

test("phrase searches use FTS before falling back to broad LIKE scans", async () => {
  const src = (await Promise.all((await fs.readdir(path.resolve(process.cwd(), "src/services"))).filter((f) => /^search.*\.ts$/.test(f)).sort().map((f) => fs.readFile(path.resolve(process.cwd(), "src/services", f), "utf8")))).join("\n").replace(/^export /gm, "");
  const searchQueryAnalysisSrc = await fs.readFile(path.resolve(process.cwd(), "src/services/search-query-analysis.ts"), "utf8");
  const searchConceptsSrc = await fs.readFile(path.resolve(process.cwd(), "src/services/search-concepts.ts"), "utf8");
  const migration = await fs.readFile(searchFtsMigrationPath, "utf8");

  assert.match(migration, /CREATE VIRTUAL TABLE IF NOT EXISTS search_chunks_fts USING fts5/);
  assert.match(migration, /CREATE TRIGGER IF NOT EXISTS document_chunks_ai_search_fts/);
  assert.match(migration, /CREATE TRIGGER IF NOT EXISTS retrieval_search_chunks_ai_search_fts/);
  assert.match(src, /async function ensureSearchFts\(env: Env\): Promise<boolean>/);
  assert.match(searchConceptsSrc, /function phraseSearchFtsQuery[\s\S]*const normalizedQuery = precomputed\?\.normalizedQuery \?\? normalizeWhitespace\(normalize\(query \|\| ""\)\)[\s\S]*const groups = precomputed\?\.normalizedGroups \?\? phraseConceptGroups\(normalizedQuery\)[\s\S]*const phraseTokens = precomputed\?\.phraseTokens \?\? meaningfulPhraseTokens\(normalizedQuery\)[\s\S]*ftsQuote\(phraseTokens\.join\(" "\)\)/);
  assert.match(src, /async function ftsSearch\(/);
  assert.match(searchQueryAnalysisSrc, /activeStructuredFilterKinds: activeStructuredFilterKinds\(context\.filters, \{[\s\S]*requestedJudgeFilters: explicitJudgeFilters,[\s\S]*requestedIndexCodeFilters: indexCodeFilterContext\.requestedCodes[\s\S]*\}\)/);
  assert.match(src, /const requestedJudges = queryDerived\.explicitJudgeFilters/);
  assert.match(src, /const requestedCodes = queryDerived\.indexCodeFilterContext\.requestedCodes/);
  assert.match(src, /const activeStructuredKinds = queryDerived\.activeStructuredFilterKinds/);
  assert.match(src, /const phraseFtsCandidateSearch =[\s\S]*queryDerived\.phraseEvidenceQuery[\s\S]*!activeStructuredKinds\.length/);
  assert.match(src, /buildAdaptiveRecallConfig\(parsed, pageWindow, \{ activeStructuredFilterKinds: activeStructuredKinds \}\)/);
  assert.match(src, /: phraseFtsCandidateSearch\s*\?\s*\[\]/);
  assert.match(src, /phraseFtsEligible[\s\S]*await ftsSearch/);
  assert.match(src, /const adaptivePhraseFloor = recallConfig\.shortBroadIssueSearch[\s\S]*Math\.max\(pageWindow \* 6, 120\)/);
  assert.match(src, /phraseFtsSearchLimit\(recallConfig, pageWindow\)/);
  assert.doesNotMatch(src, /Math\.max\(recallConfig\.lexicalSearchLimit, 360\)/);
  assert.match(src, /const phraseFtsHasEnoughEvidence =[\s\S]*phraseFtsEligible[\s\S]*lexicalRows\.length >= Math\.min\(Math\.max\(parsed\.limit, 8\), 18\)[\s\S]*!activeStructuredKinds\.length/);
  assert.match(src, /shouldSkipVectorSearch\(effectiveQuery, parsed\.filters, queryType\) \|\| phraseFtsHasEnoughEvidence/);
  assert.match(src, /if \(!skipLexicalForVectorFirstIssueSearch && lexicalRows\.length === 0\)[\s\S]*await lexicalSearch/);
});

test("phrase snippets prefer phrase evidence and avoid common drift cases", async () => {
  const src = (await Promise.all((await fs.readdir(path.resolve(process.cwd(), "src/services"))).filter((f) => /^search.*\.ts$/.test(f)).sort().map((f) => fs.readFile(path.resolve(process.cwd(), "src/services", f), "utf8")))).join("\n").replace(/^export /gm, "");
  const searchClassificationSrc = await fs.readFile(path.resolve(process.cwd(), "src/services/search-query-classification.ts"), "utf8");
  const searchConceptsSrc = await fs.readFile(path.resolve(process.cwd(), "src/services/search-concepts.ts"), "utf8");

  assert.match(src, /const authorityPhraseCoverage = authoritySnippet\s*\? phraseConceptCoverage/);
  assert.match(src, /const factPhraseCoverage = factSnippet\s*\? phraseConceptCoverage/);
  assert.match(src, /factPhraseCoverage\.matchedCount > authorityPhraseCoverage\.matchedCount/);
  assert.match(src, /room_heat_water_heater_drift_penalty/);
  assert.match(src, /phrase_capital_improvement_cost_drift_penalty/);
  assert.match(src, /function leakWindowContextAdjustment\([\s\S]*precomputed\?: \{ normalizedQuery\?: string; normalizedText\?: string \}[\s\S]*\): \{ score: number; reason: string \| null \}/);
  assert.match(src, /leak_window_split_evidence_penalty/);
  assert.match(src, /leak_window_bathroom_context_boost/);
  assert.match(src, /leak_window_missing_bathroom_penalty/);
  assert.match(src, /phraseFtsSearchLimit\(recallConfig, pageWindow\)/);
  assert.match(src, /phrase_exact_fact_evidence_boost/);
  assert.match(src, /document_phrase_exact_fact_boost/);
  assert.match(src, /decision_layer_exact_phrase_evidence_boost/);
  assert.match(src, /queryDerived\.phraseEvidenceQuery[\s\S]*Math\.min\(0\.04, Math\.max\(0, docHitCount - 1\) \* 0\.01\)/);
  assert.match(src, /phrase_generic_legal_standard_penalty/);
});

test("search scoring uses per-search derived query context in hot row scoring", async () => {
  const src = (await Promise.all((await fs.readdir(path.resolve(process.cwd(), "src/services"))).filter((f) => /^search.*\.ts$/.test(f)).sort().map((f) => fs.readFile(path.resolve(process.cwd(), "src/services", f), "utf8")))).join("\n").replace(/^export /gm, "");
  const searchQueryAnalysisSrc = await fs.readFile(path.resolve(process.cwd(), "src/services/search-query-analysis.ts"), "utf8");
  const searchTypesSrc = await fs.readFile(path.resolve(process.cwd(), "src/services/search-types.ts"), "utf8");
  const searchClassificationSrc = await fs.readFile(path.resolve(process.cwd(), "src/services/search-query-classification.ts"), "utf8");
  const searchConceptsSrc = await fs.readFile(path.resolve(process.cwd(), "src/services/search-concepts.ts"), "utf8");

  assert.match(searchTypesSrc, /interface QueryDerivedContext/);
  assert.match(src, /context\.derived = buildQueryDerivedContext\(context\)/);
  assert.match(searchTypesSrc, /rowSearchableTextCache\?: Map<string, string>/);
  assert.match(searchTypesSrc, /normalizedRowSearchableTextCache\?: Map<string, string>/);
  assert.match(searchTypesSrc, /normalizedRowChunkTextCache\?: Map<string, string>/);
  assert.match(searchTypesSrc, /rowMetadataCache\?: Map<string, RowMetadata>/);
  assert.match(searchTypesSrc, /interface RowMetadata \{[\s\S]*normalizedIndexCodes: string\[\]/);
  assert.match(searchTypesSrc, /interface RowMetadata \{[\s\S]*normalizedTitle: string;[\s\S]*normalizedCitation: string;/);
  assert.match(src, /normalizedTitle: normalize\(row\.title\)/);
  assert.match(src, /normalizedCitation: normalize\(row\.citation\)/);
  assert.match(searchConceptsSrc, /precomputed\?: \{ normalizedQuery\?: string; normalizedGroups\?: string\[\]\[\]; normalizedText\?: string \}/);
  assert.match(src, /const normalizedText = precomputed\?\.normalizedText \?\? normalize\(text \|\| ""\)/);
  assert.match(src, /function rowHasLiteralKeywordMatch\([\s\S]*context: SearchContext,[\s\S]*precomputed: \{ literalTokens: string\[\] \}/);
  assert.match(src, /const tokens = precomputed\.literalTokens/);
  assert.match(src, /function phraseConceptGuardPasses\(row: ChunkRow, query: string, context: SearchContext\): boolean[\s\S]*phraseConceptCoverage\([\s\S]*\{ \.\.\.phraseConceptContext, normalizedText: cachedNormalizedSearchableText\(row, context\) \}/);
  assert.match(src, /function rowMatchesQueryGuard[\s\S]*const queryDerived = getQueryDerivedContext\(context\)/);
  assert.match(src, /function rowMatchesQueryGuard[\s\S]*if \(queryDerived\.antInfestationQuery\) \{/);
  assert.match(src, /function rowMatchesQueryGuard[\s\S]*if \(queryDerived\.homeownersExemptionQuery\) \{/);
  assert.match(src, /const boundaryGuardTerms = queryDerived\.keywordBoundaryGuardTerms/);
  assert.match(src, /rowHasLiteralKeywordMatch\(row, context, \{ literalTokens: queryDerived\.literalKeywordTokens \}\)/);
  assert.match(src, /const queryDerived = getQueryDerivedContext\(context\)/);
  assert.match(src, /const structuralIntent = queryDerived\.structuralIntent/);
  assert.match(searchQueryAnalysisSrc, /const q = precomputed\?\.normalizedQuery \?\? normalize\(context\.query \|\| ""\)/);
  assert.match(searchQueryAnalysisSrc, /structuralIntent: isStructuralIntent\(context, normalizedQueryContext\)/);
  assert.match(src, /if \(!structuralIntent && context\.queryType !== "citation_lookup" && vectorDominance && isLowSignalTabularChunkType\(normalizedChunkType\)\)/);
  assert.match(searchQueryAnalysisSrc, /normalizedIssueTerms: issueTerms\.map\(\(term\) => normalize\(term\)\)\.filter\(Boolean\)/);
  assert.match(searchQueryAnalysisSrc, /normalizedProceduralTerms: proceduralTerms\.map\(\(term\) => normalize\(term\)\)\.filter\(Boolean\)/);
  assert.match(searchQueryAnalysisSrc, /\(precomputed\?\.issueTerms \?\? inferIssueTerms\(query, normalizedQueryContext\)\)/);
  assert.match(searchQueryAnalysisSrc, /const sentenceSecondaryTokens = sentenceSecondaryFactTokens\(context\.query, \{ issueTerms, normalizedQuery \}\)/);
  assert.match(searchQueryAnalysisSrc, /const broadIssueQuery = fullTokens\.length <= 12 && inferredIssueTerms\.length > 0/);
  assert.match(searchQueryAnalysisSrc, /const recallIssueTerms = inferIssueTerms\(parsed\.query \|\| ""\)/);
  assert.match(searchQueryAnalysisSrc, /const recallIssueTermContext = \{ issueTerms: recallIssueTerms \}/);
  assert.match(searchQueryAnalysisSrc, /const issueGuidedSearch = isIssueGuidedSearch\(parsed, recallIssueTermContext\)/);
  assert.match(searchQueryAnalysisSrc, /const shortBroadIssueSearch = isShortBroadIssueSearch\(parsed, recallIssueTermContext\)/);
  assert.match(searchQueryAnalysisSrc, /const activeKinds = precomputed\?\.activeStructuredFilterKinds \?\? activeStructuredFilterKinds\(parsed\.filters\)/);
  assert.match(searchQueryAnalysisSrc, /function activeStructuredFilterKinds\([\s\S]*precomputed\?: \{ requestedJudgeFilters\?: string\[\]; requestedIndexCodeFilters\?: string\[\] \}/);
  assert.match(src, /function applyCombinedFilterRecoveryBoost[\s\S]*getQueryDerivedContext\(context\)\.activeStructuredFilterKinds/);
  assert.match(src, /const bypassScopedKeywordRecall = keywordFamilyRecallQuery && requestedJudges\.length > 0/);
  assert.match(src, /const explicitJudgeFilters = requestedJudges/);
  assert.match(src, /requestedCodes\.includes\("G44"\)/);
  assert.match(src, /requestedCodes\.includes\("G76"\)/);
  assert.doesNotMatch(src, /const requestedLegacyPestCodes = requestedIndexCodeFilters\(parsed\.filters\)/);
  assert.match(src, /const context: SearchContext = \{[\s\S]*query: effectiveQuery,[\s\S]*retrievalQuery,[\s\S]*vectorQuery,[\s\S]*queryType,[\s\S]*filters: parsed\.filters,[\s\S]*snippetMaxLength: parsed\.snippetMaxLength[\s\S]*\}/);
  assert.match(src, /context\.derived = buildQueryDerivedContext\(context\)/);
  assert.match(src, /const ownerMoveInIssueSearch = queryDerived\.retrievalOwnerMoveInIssueQuery/);
  assert.match(src, /const wrongfulEvictionIssueSearch = queryDerived\.retrievalWrongfulEvictionIssueQuery/);
  assert.match(src, /const infestationAliasIssueSearch = queryDerived\.retrievalInfestationAliasQuery/);
  assert.match(src, /const vectorFirstIssueSearch = queryDerived\.vectorFirstIssueQuery/);
  assert.match(src, /const lockoutSpecificityRequired = queryDerived\.retrievalLockoutSpecificityRequired/);
  assert.match(src, /const habitabilitySpecificityRequired = queryDerived\.retrievalHabitabilitySpecificityRequired/);
  assert.doesNotMatch(src, /const vectorFirstIssueSearch = isVectorFirstIssueSearch\(retrievalQuery\)/);
  assert.match(src, /const skipLexicalForVectorFirstIssueSearch =[\s\S]*recallConfig\.issueGuidedSearch &&[\s\S]*vectorFirstIssueSearch &&[\s\S]*lexicalScopeDocumentIds\.length === 0/);
  assert.match(src, /const phraseLexicalTerms = boundLexicalTermsForD1\(lexicalTerms\(phraseQuery\), 9, params\.length \+ 1\)/);
  assert.match(src, /buildLexicalMatchClause\("rs\.chunk_text", "d\.citation", "d\.title", "d\.author_name", phraseLexicalTerms\)/);
  assert.match(src, /buildLexicalRankExpr\("rs\.chunk_text", "d\.citation", "d\.title", "d\.author_name", "rs\.section_label", phraseLexicalTerms\)/);
  assert.match(src, /options\?: \{ allowActiveDocumentChunkSearch\?: boolean; ftsQuery\?: string \}/);
  assert.match(src, /const ftsQuery = options\?\.ftsQuery \?\? phraseSearchFtsQuery\(query\)/);
  assert.match(src, /const phraseFtsQuery = phraseSearchFtsQuery\(effectiveQuery, \{[\s\S]*normalizedQuery: normalizedEffectiveQuery,[\s\S]*normalizedGroups: queryDerived\.normalizedPhraseConceptGroups,[\s\S]*phraseTokens: queryDerived\.phraseTokens[\s\S]*\}\)/);
  assert.match(src, /phraseFtsEligible[\s\S]*phraseFtsQuery\.length > 0/);
  assert.match(src, /allowActiveDocumentChunkSearch: allowDocumentChunkLexicalSearch, ftsQuery: phraseFtsQuery/);
  assert.match(searchQueryAnalysisSrc, /const queryTokens = tokenize\(context\.query\)/);
  assert.match(searchQueryAnalysisSrc, /const phraseTokens = meaningfulPhraseTokens\(context\.query\)/);
  assert.match(searchQueryAnalysisSrc, /phraseTokens,/);
  assert.match(searchConceptsSrc, /function phraseConceptGroups\(query: string, precomputed\?: \{ phraseTokens\?: string\[\] \}\): string\[\]\[\] \{\s*const tokens = precomputed\?\.phraseTokens \?\? meaningfulPhraseTokens\(query\)/);
  assert.match(searchTypesSrc, /normalizedRetrievalPhraseConceptGroups: string\[\]\[\]/);
  assert.match(searchQueryAnalysisSrc, /const normalizedRetrievalPhraseConceptGroups = phraseConceptGroups\(context\.retrievalQuery\)\.map/);
  assert.match(searchQueryAnalysisSrc, /longQueryTokens: queryTokens\.filter\(\(token\) => token\.length > 3\)/);
  assert.match(searchQueryAnalysisSrc, /sentencePhraseOverlapTokens: queryTokens\.filter\(\(token\) => token\.length > 2 && !STOPWORD_TOKENS\.has\(token\)\)/);
  assert.match(searchQueryAnalysisSrc, /normalizedPrimarySignals: primarySignals\.map\(\(signal\) => normalize\(signal\)\)/);
  assert.match(src, /\.\.\.queryDerived\.longQueryTokens/);
  assert.match(src, /const issueTerms = queryDerived\.normalizedIssueTerms/);
  assert.match(searchQueryAnalysisSrc, /precomputed\?: \{ normalizedText\?: string; normalizedSignal\?: string \}/);
  assert.match(src, /const normalizedText = precomputed\?\.normalizedText \?\? normalize\(text\)/);
  assert.match(searchQueryAnalysisSrc, /hasOwnerMoveInPhrase\(normalizedText, \{ normalizedText \}\)/);
  assert.match(searchQueryAnalysisSrc, /hasOwnerMoveInPhrase\(normalized, \{ normalizedText: normalized \}\)/);
  assert.match(searchQueryAnalysisSrc, /hasWrongfulEvictionPhrase\(normalized, \{ normalizedText: normalized \}\)/);
  assert.match(searchQueryAnalysisSrc, /containsWholeWord\(normalized, "awe", \{ normalizedText: normalized \}\)/);
  assert.match(searchQueryAnalysisSrc, /const normalizedTextContext = \{ normalizedText \}/);
  assert.match(searchQueryAnalysisSrc, /hasAccommodationContext\(normalizedText, normalizedTextContext\)/);
  assert.match(searchQueryAnalysisSrc, /hasPackageSecurityContext\(normalizedText, normalizedTextContext\)/);
  assert.match(searchQueryAnalysisSrc, /hasWindowsContext\(normalizedText, normalizedTextContext\)/);
  assert.match(searchQueryAnalysisSrc, /hasWrongfulEvictionLockoutContext\(normalizedText, normalizedTextContext\)/);
  assert.match(searchQueryAnalysisSrc, /const normalizedText = \{ normalizedText: normalized \}/);
  assert.match(searchQueryAnalysisSrc, /hasOwnerMoveInPhrase\(normalized, normalizedText\)/);
  assert.match(searchQueryAnalysisSrc, /hasWrongfulEvictionPhrase\(normalized, normalizedText\)/);
  assert.match(src, /const normalizedPrimarySignals = queryDerived\.normalizedPrimarySignals/);
  assert.match(src, /normalizedSignal: precomputed\?\.normalizedSignals\?\.\[index\]/);
  assert.match(src, /issueSignalHitCount\(loweredSnippet, primarySignals,[\s\S]*normalizedText: loweredSnippet,[\s\S]*normalizedSignals: normalizedPrimarySignals/);
  assert.match(src, /const normalizedQueryContext = \{ normalizedQuery \}/);
  assert.match(searchQueryAnalysisSrc, /const q = precomputed\?\.normalizedQuery \?\? normalize\(context\.query \|\| ""\)/);
  assert.match(searchQueryAnalysisSrc, /queryIntent: inferQueryIntent\(context, normalizedQueryContext\)/);
  assert.match(src, /const referencedJudges = queryDerived\.referencedJudges/);
  assert.match(searchQueryAnalysisSrc, /judgeDrivenQuery: isJudgeDrivenQuery\(context\.query, \{ referencedJudges, issueTerms, proceduralTerms \}\)/);
  assert.match(searchQueryAnalysisSrc, /phraseEvidenceQuery: isPhraseEvidenceQuery\(context\.query, \{ normalizedGroups: normalizedPhraseConceptGroups \}\)/);
  assert.match(src, /queryDerived\.phraseEvidenceQuery/);
  assert.match(searchQueryAnalysisSrc, /const literalKeywordTokensForQuery = literalKeywordTokens\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /const sentenceStyleReasoningQuery = isSentenceStyleReasoningQuery\(context\)/);
  assert.match(searchQueryAnalysisSrc, /function isMarketConditionReasoningQuery\([\s\S]*precomputed\?: \{ normalizedQuery\?: string; sentenceStyleReasoningQuery\?: boolean \}/);
  assert.match(searchQueryAnalysisSrc, /const sentenceStyleReasoningQuery = precomputed\?\.sentenceStyleReasoningQuery \?\? isSentenceStyleReasoningQuery\(context\)/);
  assert.match(searchQueryAnalysisSrc, /marketConditionReasoningQuery: isMarketConditionReasoningQuery\(context,[\s\S]*normalizedQuery,[\s\S]*sentenceStyleReasoningQuery/);
  assert.match(src, /function marketConditionReasoningScore\(query: string, text: string, precomputed\?: \{ normalizedQuery\?: string; normalizedText\?: string \}\): number \{\s*const normalizedQuery = precomputed\?\.normalizedQuery \?\? normalize\(query\)[\s\S]*const normalizedText = precomputed\?\.normalizedText \?\? normalize\(text\)/);
  assert.match(src, /marketConditionReasoningScore\(context\.query, searchableText, \{[\s\S]*normalizedQuery: queryDerived\.normalizedQuery,[\s\S]*normalizedText: loweredSnippet[\s\S]*\}\)/);
  assert.match(searchClassificationSrc, /function isAntInfestationQuery\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): boolean \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)[\s\S]*isAntQuery\(query, normalizedQueryContext\) && isInfestationAliasQuery\(query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /antInfestationQuery: isAntInfestationQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /retrievalInfestationAliasQuery: isInfestationAliasQuery\(context\.retrievalQuery, normalizedRetrievalQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /retrievalOwnerMoveInIssueQuery: isOwnerMoveInIssueSearch\(context\.retrievalQuery, normalizedRetrievalQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /retrievalWrongfulEvictionIssueQuery: isWrongfulEvictionIssueSearch\(context\.retrievalQuery, normalizedRetrievalQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /retrievalLockoutSpecificityRequired: requiresLockoutSpecificity\(context\.retrievalQuery, normalizedRetrievalQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /retrievalHabitabilitySpecificityRequired: requiresHabitabilitySpecificity\(context\.retrievalQuery,[\s\S]*normalizedQuery: normalizedRetrievalQuery,[\s\S]*primarySignals: retrievalPrimarySignals/);
  assert.match(searchQueryAnalysisSrc, /vectorFirstIssueQuery: isVectorFirstIssueSearch\(context\.retrievalQuery, normalizedRetrievalQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /function inferIssueTerms\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const q = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)/);
  assert.match(searchQueryAnalysisSrc, /function inferProceduralTerms\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const q = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)/);
  assert.match(searchQueryAnalysisSrc, /const issueTerms = inferIssueTerms\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /const proceduralTerms = inferProceduralTerms\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /function shouldSkipVectorSearch[\s\S]*inferIssueTerms\(query, normalizedQueryContext\)\.length > 0 && tokenCount <= 12/);
  assert.match(searchQueryAnalysisSrc, /function primaryIssueSignals\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)/);
  assert.match(searchQueryAnalysisSrc, /function sentenceIssueAnchorTerms\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)/);
  assert.match(searchQueryAnalysisSrc, /function sentenceSecondaryFactTokens\(query: string, precomputed\?: \{ issueTerms\?: string\[\]; normalizedQuery\?: string \}\): string\[\] \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)[\s\S]*inferIssueTerms\(query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /const retrievalPrimarySignals = primaryIssueSignals\(context\.retrievalQuery, normalizedRetrievalQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /const sentenceIssueAnchors = sentenceIssueAnchorTerms\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /const sentenceSecondaryTokens = sentenceSecondaryFactTokens\(context\.query, \{ issueTerms, normalizedQuery \}\)/);
  assert.match(searchQueryAnalysisSrc, /const primarySignals = primaryIssueSignals\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /keywordFamilyRecallQuery: isKeywordFamilyRecallQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /const keywordFamilyRecallQuery = queryType === "keyword" && queryDerived\.keywordFamilyRecallQuery/);
  assert.match(searchQueryAnalysisSrc, /function matchedCuratedKeywordFamilies\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): CuratedKeywordFamily\[\] \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)[\s\S]*isAntInfestationQuery\(query, \{ normalizedQuery: normalized \}\)/);
  assert.match(searchQueryAnalysisSrc, /function literalKeywordTokens\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)[\s\S]*isInfestationAliasQuery\(query, \{ normalizedQuery: normalized \}\)/);
  assert.match(searchQueryAnalysisSrc, /function isLiteralKeywordQuery\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): boolean \{\s*return literalKeywordTokens\(query, precomputed\)\.length > 0/);
  assert.match(searchQueryAnalysisSrc, /function isKeywordFamilyRecallQuery[\s\S]*isLiteralKeywordQuery\(query, \{ normalizedQuery: normalized \}\)[\s\S]*matchedCuratedKeywordFamilies\(query, \{ normalizedQuery: normalized \}\)\.length > 0/);
  assert.match(searchQueryAnalysisSrc, /const literal = literalKeywordTokens\(query, \{ normalizedQuery: normalized \}\)/);
  assert.match(searchQueryAnalysisSrc, /function curatedKeywordWholeWordExpansionTerms\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const expansions = new Set<string>\(\)[\s\S]*matchedCuratedKeywordFamilies\(query, precomputed\)/);
  assert.match(searchQueryAnalysisSrc, /function keywordCandidateTerms\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)[\s\S]*curatedKeywordWholeWordExpansionTerms\(query, \{ normalizedQuery: normalized \}\)[\s\S]*literalKeywordTokens\(query, \{ normalizedQuery: normalized \}\)/);
  assert.match(src, /function keywordExecutionTerms\(query: string, precomputed\?: \{ normalizedQuery\?: string; normalizedGroups\?: string\[\]\[\] \}\): string\[\] \{\s*const normalizedQuery = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)[\s\S]*const normalizedGroups = precomputed\?\.normalizedGroups \?\? phraseConceptGroups\(normalizedQuery\)[\s\S]*keywordCandidateTerms\(query, \{ normalizedQuery \}\)/);
  assert.match(src, /const terms = boundLexicalTermsForD1\(keywordCandidateTerms\(query, normalizedQueryContext\), 9, documentScopeParams\.length \+ 1\)/);
  assert.match(src, /const wholeWordGuarded = keywordBoundaryGuardTerms\(query, normalizedQueryContext\)\.length > 0/);
  assert.match(src, /const keywordTermsOverride =[\s\S]*queryType === "keyword"[\s\S]*keywordExecutionTerms\(effectiveQuery, \{[\s\S]*normalizedQuery: normalizedEffectiveQuery,[\s\S]*normalizedGroups: queryDerived\.normalizedPhraseConceptGroups[\s\S]*\}\)[\s\S]*: undefined/);
  assert.match(searchQueryAnalysisSrc, /curatedKeywordFamilyQuery: matchedCuratedKeywordFamilies\(context\.query, normalizedQueryContext\)\.length > 0/);
  assert.match(searchQueryAnalysisSrc, /literalKeywordQuery: literalKeywordTokensForQuery\.length > 0/);
  assert.match(searchQueryAnalysisSrc, /literalKeywordTokens: literalKeywordTokensForQuery/);
  assert.match(src, /queryDerived\.literalKeywordQuery \|\| queryDerived\.retrievalInfestationAliasQuery \|\| queryDerived\.curatedKeywordFamilyQuery/);
  assert.match(src, /queryDerived\.literalKeywordQuery \|\| queryDerived\.curatedKeywordFamilyQuery/);
  assert.match(searchConceptsSrc, /function keywordSurfaceVariants\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)/);
  assert.match(searchQueryAnalysisSrc, /function curatedKeywordExpansionTerms\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const expansions = new Set<string>\(\)[\s\S]*matchedCuratedKeywordFamilies\(query, precomputed\)/);
  assert.match(searchQueryAnalysisSrc, /function curatedKeywordLexicalExpansionTerms\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const expansions = new Set<string>\(\)[\s\S]*matchedCuratedKeywordFamilies\(query, precomputed\)/);
  assert.match(searchConceptsSrc, /function phrasePriorityLexicalTerms[\s\S]*const normalizedQueryContext = \{ normalizedQuery: full \}[\s\S]*keywordSurfaceVariants\(full, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /function lexicalTerms[\s\S]*const normalizedQueryContext = \{ normalizedQuery: normalizedFull \}[\s\S]*keywordSurfaceVariants\(full, normalizedQueryContext\)[\s\S]*curatedKeywordLexicalExpansionTerms\(full, normalizedQueryContext\)[\s\S]*matchedCuratedKeywordFamilies\(full, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /function wholeWordLexicalTerms[\s\S]*const normalizedQueryContext = \{ normalizedQuery: normalize\(full\) \}[\s\S]*keywordSurfaceVariants\(full, normalizedQueryContext\)[\s\S]*curatedKeywordWholeWordExpansionTerms\(full, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /function keywordBoundaryGuardTerms\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)[\s\S]*curatedKeywordExpansionTerms\(query, normalizedQueryContext\)[\s\S]*keywordSurfaceVariants\(query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /keywordBoundaryGuardTerms: keywordBoundaryGuardTerms\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /if \(queryDerived\.literalKeywordQuery\) \{/);
  assert.match(searchQueryAnalysisSrc, /leakWindowQuery: isLeakWindowQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /if \(queryDerived\.leakWindowQuery\) \{/);
  assert.match(searchQueryAnalysisSrc, /ownerMoveInFollowThroughRequired: requiresOwnerMoveInFollowThroughSpecificity\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /habitabilityServiceQuery: hasHabitabilityServiceRestorationSignals\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /requiredHabitabilitySignals: primarySignals\.filter\(\(signal\) =>[\s\S]*\["mold", "heat", "hot water", "rodent", "cockroach", "bed bug"\]\.includes\(signal\)/);
  assert.match(searchQueryAnalysisSrc, /lockoutSpecificityRequired: requiresLockoutSpecificity\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /const conditionSignals = precomputed\?\.primarySignals \?\? requiredHabitabilityPrimarySignals\(query, \{ normalizedQuery: normalized \}\)/);
  assert.match(searchQueryAnalysisSrc, /function requiredHabitabilityPrimarySignals\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*return primaryIssueSignals\(query, precomputed\)\.filter/);
  assert.match(searchQueryAnalysisSrc, /function issueQueryIndexCodeHints\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)/);
  assert.match(searchQueryAnalysisSrc, /function issueQueryPhraseHints\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)[\s\S]*inferIssueTerms\(query, normalizedQueryContext\)[\s\S]*issueQueryIndexCodeHints\(query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /function issueQueryReferenceHints\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): \{ rulesSections: string\[\]; ordinanceSections: string\[\] \} \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)/);
  assert.match(searchQueryAnalysisSrc, /function lockoutScopePhraseHints\(query: string, precomputed\?: \{ normalizedQuery\?: string \}\): string\[\] \{\s*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)[\s\S]*requiresLockoutSpecificity\(query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /function habitabilityScopePhraseHints\([\s\S]*precomputed\?: \{ normalizedQuery\?: string; primarySignals\?: string\[\] \}[\s\S]*const normalized = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)[\s\S]*requiredHabitabilityPrimarySignals\(query, normalizedQueryContext\)/);
  assert.match(src, /const codeHints = issueQueryIndexCodeHints\(query, normalizedQueryContext\)/);
  assert.match(src, /const phraseHints = issueQueryPhraseHints\(query, normalizedQueryContext\)/);
  assert.match(src, /const manualReferenceHints = issueQueryReferenceHints\(query, normalizedQueryContext\)/);
  assert.match(src, /const phraseHints = lockoutScopePhraseHints\(query, normalizedQueryContext\)/);
  assert.match(src, /habitabilityScopePhraseHints\(query, \{ normalizedQuery \}\)/);
  assert.match(searchQueryAnalysisSrc, /lockBoxQuery: isLockBoxQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /harassmentRetaliationQuery: \/\\bharassment\|retaliation\\b\/\.test\(normalizedQuery\)/);
  assert.match(searchQueryAnalysisSrc, /wrongfulEvictionQuery: hasWrongfulEvictionPhrase\(normalizedQuery, \{ normalizedText: normalizedQuery \}\)/);
  assert.match(searchQueryAnalysisSrc, /wrongfulEvictionIssueQuery: isWrongfulEvictionIssueSearch\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /coolingIssueQuery: isCoolingIssueQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /conditionIssueQuery: issueTerms\.length > 0/);
  assert.match(searchQueryAnalysisSrc, /noticeProceduralQuery: proceduralTerms\.length > 0/);
  assert.match(searchQueryAnalysisSrc, /strongIssueEvidenceRequired: requiresStrongIssueEvidence\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /accommodationQuery: isAccommodationQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /homeownersExemptionQuery: isHomeownersExemptionQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /selfEmployedQuery: isSelfEmployedQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /adjudicatedQuery: isAdjudicatedQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /socialMediaQuery: isSocialMediaQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /caregiverQuery: isCaregiverQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /mootQuery: isMootQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /divorceQuery: isDivorceQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /remoteWorkQuery: isRemoteWorkQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /collegeQuery: isCollegeQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /coLivingQuery: isCoLivingQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /buyoutQuery: isBuyoutQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /buyoutPressureQuery: isBuyoutPressureQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /evictionProtectionQuery: isEvictionProtectionQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /packageSecurityQuery: isPackageSecurityQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /cameraPrivacyQuery: isCameraPrivacyQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /poopQuery: isPoopQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /dogQuery: isDogQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /intercomQuery: isIntercomQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /garageSpaceQuery: isGarageSpaceQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /commonAreasQuery: isCommonAreasQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /stairsQuery: isStairsQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /porchQuery: isPorchQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /windowsQuery: isWindowsQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /section8Query: isSection8Query\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /unlawfulDetainerQuery: isUnlawfulDetainerQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /roomHeatQuery: isRoomHeatQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /queryMentionsMold: containsWholeWord\(context\.query, "mold", \{ normalizedText: normalizedQuery \}\)/);
  assert.match(searchQueryAnalysisSrc, /queryMentionsMildew: containsWholeWord\(context\.query, "mildew", \{ normalizedText: normalizedQuery \}\)/);
  assert.match(searchQueryAnalysisSrc, /normalizedSentenceIssueAnchors: sentenceIssueAnchors\.map\(\(term\) => normalize\(term\)\)/);
  assert.match(searchQueryAnalysisSrc, /normalizedSentenceSecondaryTokens: sentenceSecondaryTokens\.map\(\(term\) => normalize\(term\)\)/);
  assert.match(searchQueryAnalysisSrc, /normalizedSentenceFactualTokens = uniq\(\[\.\.\.sentenceIssueAnchors, \.\.\.sentenceSecondaryTokens\]\)/);
  assert.match(src, /precomputedFactualTokens \?\?/);
  assert.match(src, /const normalizedText = precomputed\?\.normalizedText \?\? normalize\(text \|\| ""\)/);
  assert.match(src, /sentenceFactualTokenMetrics\(context\.query, searchableText, queryDerived\.normalizedSentenceFactualTokens,[\s\S]*normalizedText: loweredSnippet/);
  assert.match(searchQueryAnalysisSrc, /normalizedPhraseConceptGroups = phraseConceptGroups\(context\.query, \{ phraseTokens \}\)\.map/);
  assert.match(src, /precomputed\?\.normalizedGroups \?\?/);
  assert.match(src, /phraseConceptCoverage\(context\.query, searchableText,[\s\S]*queryDerived\.normalizedPhraseConceptGroups/);
  assert.match(src, /function exactMultiWordPhraseScore\([\s\S]*precomputed\?: \{ normalizedGroups\?: string\[\]\[\]; normalizedQuery\?: string; normalizedText\?: string; phraseTokens\?: string\[\] \}[\s\S]*const tokens = precomputed\?\.phraseTokens \?\? meaningfulPhraseTokens\(query\)[\s\S]*phraseConceptCoverage\(query, text, \{[\s\S]*normalizedGroups: precomputed\?\.normalizedGroups,[\s\S]*normalizedQuery: precomputed\?\.normalizedQuery/);
  assert.match(src, /const normalizedCoverageText = precomputed\?\.normalizedText \?\? normalize\(text\)/);
  assert.match(src, /isLeakWindowQuery\(query,[\s\S]*hasLeakWindowContext\(text, \{ normalizedText: normalizedCoverageText \}\)/);
  assert.match(src, /exactMultiWordPhraseScore\(context\.query, searchableText, \{[\s\S]*normalizedGroups: queryDerived\.normalizedPhraseConceptGroups,[\s\S]*normalizedQuery: queryDerived\.normalizedQuery,[\s\S]*normalizedText: loweredSnippet,[\s\S]*phraseTokens: queryDerived\.phraseTokens[\s\S]*\}\)/);
  assert.match(src, /const aggregatedText = candidates\.map\(\(candidate\) => cachedNormalizedSearchableText\(candidate\.row, context\)\)\.join\(" "\)/);
  assert.match(src, /function buildDocumentEvidenceSummary[\s\S]*sentenceFactualTokenMetrics\(context\.query, searchableText, queryDerived\.normalizedSentenceFactualTokens,[\s\S]*normalizedText/);
  assert.match(src, /function buildDocumentEvidenceSummary[\s\S]*issueSignalHitCount\(aggregatedText, primarySignals,[\s\S]*normalizedSignals: queryDerived\.normalizedPrimarySignals/);
  assert.match(src, /function buildDocumentEvidenceSummary[\s\S]*issueSignalHitCount\(normalizedText, primarySignals,[\s\S]*normalizedSignals: queryDerived\.normalizedPrimarySignals/);
  assert.match(src, /function representativeChunkDisplayScore[\s\S]*sentenceFactualTokenMetrics\(context\.query, searchableText, queryDerived\.normalizedSentenceFactualTokens,[\s\S]*exactMultiWordPhraseScore\(context\.query, searchableText, \{[\s\S]*normalizedGroups: queryDerived\.normalizedPhraseConceptGroups,[\s\S]*normalizedQuery: queryDerived\.normalizedQuery,[\s\S]*normalizedText,[\s\S]*phraseTokens: queryDerived\.phraseTokens[\s\S]*\}\)/);
  assert.match(src, /function representativeChunkDisplayScore[\s\S]*issueSignalHitCount\(normalizedText, primarySignals,[\s\S]*normalizedSignals: queryDerived\.normalizedPrimarySignals/);
  assert.match(src, /function authorityPassageScore[\s\S]*sentenceFactualTokenMetrics\(context\.query, searchableText, queryDerived\.normalizedSentenceFactualTokens,[\s\S]*exactMultiWordPhraseScore\(context\.query, searchableText, \{[\s\S]*normalizedGroups: queryDerived\.normalizedPhraseConceptGroups,[\s\S]*normalizedQuery: queryDerived\.normalizedQuery,[\s\S]*normalizedText,[\s\S]*phraseTokens: queryDerived\.phraseTokens[\s\S]*\}\)/);
  assert.match(src, /function authorityPassageScore[\s\S]*issueSignalHitCount\(normalizedText, queryDerived\.primarySignals,[\s\S]*normalizedSignals: queryDerived\.normalizedPrimarySignals/);
  assert.match(src, /function supportingFactAnchorDiagnostics[\s\S]*sentenceFactualTokenMetrics\(context\.query, searchableText, queryDerived\.normalizedSentenceFactualTokens,[\s\S]*normalizedText/);
  assert.match(src, /function supportingFactAnchorDiagnostics[\s\S]*issueSignalHitCount\(normalizedText, primarySignals,[\s\S]*normalizedSignals: queryDerived\.normalizedPrimarySignals/);
  assert.match(src, /const habitabilityServiceQuery = queryDerived\.habitabilityServiceQuery/);
  assert.match(src, /const lockoutSpecificityRequired = queryDerived\.lockoutSpecificityRequired/);
  assert.match(src, /const requiredConditionSignals = queryDerived\.requiredHabitabilitySignals/);
  assert.match(src, /function fetchSupportingFactChunksByDocumentIds[\s\S]*const normalizedText = cachedNormalizedChunkText\(row, context\)/);
  assert.match(src, /const searchableText = cachedCombinedSearchableText\(row, context\)/);
  assert.match(src, /const loweredSnippet = cachedNormalizedSearchableText\(row, context\)/);
  assert.match(src, /const normalizedTextContext = \{ normalizedQuery: queryDerived\.normalizedQuery, normalizedText: loweredSnippet \}/);
  assert.match(src, /hasAccommodationContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasSection8Context\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasUnlawfulDetainerContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasOwnerMoveInContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasOwnerMoveInFollowThroughContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasEmploymentAccommodationDrift\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasLockBoxContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasHomeownersExemptionContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCameraPrivacyContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasPackageDeliverySecurityContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasPackageSecurityContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasDogPolicyContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasDogParkContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasDogContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCollegeContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasSelfEmployedContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasAdjudicatedContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasSocialMediaContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCaregiverContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasPoopContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasMootContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasRemoteWorkContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasDivorceContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasIntercomContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasGarageSpaceContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCommonAreasContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasStairsContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasPorchContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasWindowsContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCoLivingContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasBuyoutPressureContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasBuyoutContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasSection8RehabDrift\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasSection827RentIncreaseDrift\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasWrongfulEvictionLockoutContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasWrongfulEvictionContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasHarassmentContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /hasRepairNoticeContext\(searchableText, normalizedTextContext\)/);
  assert.match(src, /isHousingServicesDefinitionBoilerplate\(searchableText, normalizedTextContext\)/);
  assert.match(src, /isOwnerMoveInLegalStandardBoilerplate\(searchableText, normalizedTextContext\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*hasSection8Context\(searchableText, \{ normalizedText \}\)[\s\S]*hasBuyoutContext\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /function buildSection8UdDocumentSupportSet[\s\S]*const normalizedText = cachedNormalizedSearchableText\(row, context\)[\s\S]*hasUnlawfulDetainerContext\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /function hasWrongContextForQuery[\s\S]*const normalizedQuery = precomputed\?\.normalizedQuery \?\? normalize\(query \|\| ""\)/);
  assert.match(src, /function hasWrongContextForQuery[\s\S]*const normalizedQueryContext = \{ normalizedQuery \}/);
  assert.match(src, /function hasWrongContextForQuery[\s\S]*isPackageSecurityQuery\(query, normalizedQueryContext\)/);
  assert.match(src, /hasWrongContextForQuery\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /function rowMatchesQueryGuard[\s\S]*isShortAlphabeticQuery\(query, \{ normalizedQuery: queryDerived\.normalizedQuery \}\)[\s\S]*const trimmed = queryDerived\.normalizedQuery/);
  assert.match(src, /function buildIssueFamilyFallbackCandidates[\s\S]*return !hasWrongContextForQuery\(context\.query, searchableText, \{ normalizedQuery: queryDerived\.normalizedQuery, normalizedText \}\)/);
  assert.match(src, /function buildIssueFamilyFallbackCandidates[\s\S]*!hasSection8Context\(searchableText, \{ normalizedText \}\)[\s\S]*!hasUnlawfulDetainerContext\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /const issueFamilyDecisionScopeSeedIds[\s\S]*hasHomeownersExemptionContext\(searchableText, \{ normalizedText \}\)[\s\S]*hasCoLivingContext\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /const issueFamilyDecisionScopeSeedIds[\s\S]*hasAccommodationContext\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /queryDerived\.lockBoxQuery/);
  assert.match(src, /queryDerived\.accommodationQuery/);
  assert.match(src, /queryDerived\.homeownersExemptionQuery/);
  assert.match(src, /queryDerived\.selfEmployedQuery/);
  assert.match(src, /queryDerived\.adjudicatedQuery/);
  assert.match(src, /queryDerived\.socialMediaQuery/);
  assert.match(src, /queryDerived\.caregiverQuery/);
  assert.match(src, /queryDerived\.mootQuery/);
  assert.match(src, /queryDerived\.divorceQuery/);
  assert.match(src, /queryDerived\.remoteWorkQuery/);
  assert.match(src, /queryDerived\.collegeQuery/);
  assert.match(src, /queryDerived\.coLivingQuery/);
  assert.match(src, /queryDerived\.buyoutQuery/);
  assert.match(src, /queryDerived\.packageSecurityQuery/);
  assert.match(src, /queryDerived\.cameraPrivacyQuery/);
  assert.match(src, /queryDerived\.poopQuery/);
  assert.match(src, /queryDerived\.dogQuery/);
  assert.match(src, /queryDerived\.roomHeatQuery/);
  assert.match(src, /const GENERIC_DECISION_QUERY_TERMS = new Set\(\["decision", "decisions", "document", "documents", "case", "cases", "search"\]\)/);
  assert.match(src, /function isGenericDecisionQuery\(query: string\): boolean \{\s*return GENERIC_DECISION_QUERY_TERMS\.has\(normalize\(query\)\)/);
  assert.match(src, /function shouldSkipVectorSearch[\s\S]*const normalizedQueryContext = \{ normalizedQuery \}/);
  assert.match(src, /function shouldSkipVectorSearch[\s\S]*requiresOwnerMoveInFollowThroughSpecificity\(query, normalizedQueryContext\)/);
  assert.match(src, /function shouldSkipVectorSearch[\s\S]*isPackageSecurityQuery\(query, normalizedQueryContext\)/);
  assert.match(src, /function shouldSkipVectorSearch[\s\S]*isDivorceQuery\(query, normalizedQueryContext\)/);
  assert.match(src, /const VECTOR_SKIP_BROAD_ISSUE_TERMS = \[/);
  assert.match(src, /const VECTOR_FIRST_ISSUE_TERMS = \[/);
  assert.match(src, /const NORMALIZED_VECTOR_SKIP_BROAD_ISSUE_TERMS = VECTOR_SKIP_BROAD_ISSUE_TERMS\.map\(\(term\) => normalize\(term\)\)/);
  assert.match(src, /const NORMALIZED_VECTOR_FIRST_ISSUE_TERMS = VECTOR_FIRST_ISSUE_TERMS\.map\(\(term\) => normalize\(term\)\)/);
  assert.match(src, /NORMALIZED_VECTOR_FIRST_ISSUE_TERMS\.some\(\(term\) => normalizedQuery\.includes\(term\)\)/);
  assert.match(src, /NORMALIZED_VECTOR_SKIP_BROAD_ISSUE_TERMS\.some\(\(term\) => normalizedQuery\.includes\(term\)\)/);
  assert.match(searchQueryAnalysisSrc, /const HABITABILITY_REPORTING_HINT_TERMS = \[/);
  assert.match(searchQueryAnalysisSrc, /const HABITABILITY_REPAIR_HINT_TERMS = \[/);
  assert.match(searchQueryAnalysisSrc, /const NORMALIZED_HABITABILITY_REPORTING_HINT_TERMS = HABITABILITY_REPORTING_HINT_TERMS\.map\(\(term\) => \(\{/);
  assert.match(searchQueryAnalysisSrc, /const NORMALIZED_HABITABILITY_REPAIR_HINT_TERMS = HABITABILITY_REPAIR_HINT_TERMS\.map\(\(term\) => \(\{/);
  assert.match(searchQueryAnalysisSrc, /const HABITABILITY_REPORTING_HINT_PATTERN = \/report\|complain\|notified\|notice\|repair request\|work order\//);
  assert.match(searchQueryAnalysisSrc, /const HABITABILITY_REPAIR_HINT_PATTERN = \/repair\|restore\|service\//);
  assert.match(searchQueryAnalysisSrc, /const reportingHints = NORMALIZED_HABITABILITY_REPORTING_HINT_TERMS\.filter/);
  assert.match(searchQueryAnalysisSrc, /const repairHints = NORMALIZED_HABITABILITY_REPAIR_HINT_TERMS\.filter/);
  assert.match(searchQueryAnalysisSrc, /const normalizedInferredIssueTerms = inferredIssueTerms\.map\(\(term\) => \(\{/);
  assert.match(searchQueryAnalysisSrc, /\.filter\(\(\{ normalizedTerm \}\) => normalizedFull\.includes\(normalizedTerm\)\)/);
  assert.match(searchQueryAnalysisSrc, /\.flatMap\(\(\{ term \}\) => meaningfulLexicalTokens\(term\)\)/);
  assert.match(searchQueryAnalysisSrc, /containsWholeWord\(normalizedFull, "omi", \{ normalizedText: normalizedFull \}\)/);
  assert.match(searchQueryAnalysisSrc, /containsWholeWord\(normalizedFull, "awe", \{ normalizedText: normalizedFull \}\)/);
  assert.match(src, /const rowReferencedJudgeMatch = queryDerived\.judgeDrivenQuery/);
  assert.match(src, /const rowMetadata = cachedRowMetadata\(row, context\)/);
  assert.match(src, /const normCitation = rowMetadata\.normalizedCitation/);
  assert.match(src, /const indexCodes = rowMetadata\.normalizedIndexCodes/);
  assert.match(src, /const ruleSections = rowMetadata\.normalizedRulesSections/);
  assert.match(src, /const ordinanceSections = rowMetadata\.normalizedOrdinanceSections/);
  assert.match(src, /rowMetadata\.normalizedTitle\.includes\(queryDerived\.normalizedPartyNameFilter\)/);
  assert.match(searchQueryAnalysisSrc, /normalizedIndexCodeRelatedRulesSections: indexCodeFilterContext\.relatedRulesSections\.map\(\(item\) => normalize\(item\)\)\.filter\(Boolean\)/);
  assert.match(searchQueryAnalysisSrc, /normalizedIndexCodeRelatedOrdinanceSections: indexCodeFilterContext\.relatedOrdinanceSections\.map\(\(item\) => normalize\(item\)\)\.filter\(Boolean\)/);
  assert.match(searchQueryAnalysisSrc, /normalizedIndexCodeSearchPhrases: indexCodeFilterContext\.searchPhrases\.map\(\(item\) => normalize\(item\)\)\.filter\(Boolean\)/);
  assert.match(src, /queryDerived\.normalizedIndexCodeRelatedRulesSections\.some/);
  assert.match(src, /queryDerived\.normalizedIndexCodeRelatedOrdinanceSections\.some/);
  assert.match(src, /queryDerived\.normalizedIndexCodeSearchPhrases\.some/);
  assert.doesNotMatch(src, /if \(isDogQuery\(context\.query\)\)/);
  assert.doesNotMatch(src, /if \(isRoomHeatQuery\(context\.query\) &&/);
  assert.match(src, /const sentenceIssueAnchors = queryDerived\.normalizedSentenceIssueAnchors/);
  assert.match(src, /const sentenceSecondaryTokens = queryDerived\.normalizedSentenceSecondaryTokens/);
  assert.match(src, /const normalizedMildewText = loweredSnippet/);
  assert.match(src, /const normalizedPoopText = loweredSnippet/);
  assert.match(src, /socialSecurityDrift =\s*\/\\bsocial security\\b[\s\S]*\.test\(loweredSnippet\)/);
  assert.match(src, /camera_privacy_missing_camera_penalty/);
  assert.match(src, /package_security_sensitive_drift_penalty/);
  assert.match(src, /collegeBondDrift =\s*\/\\bcommunity college district\\b[\s\S]*\.test\(\s*loweredSnippet\s*\)/);
  assert.match(src, /remote_work_partial_phrase_boost/);
  assert.match(src, /windows_capital_improvement_drift_penalty/);
  assert.match(src, /buyout_pressure_generic_settlement_penalty/);
  assert.match(src, /const normalizedAuthoritySnippet = normalize\(authoritySnippet\)/);
  assert.match(src, /const normalizedFactSnippet = normalize\(factSnippet\)/);
  assert.match(src, /const authoritySnippetContext = \{ normalizedText: normalizedAuthoritySnippet \}/);
  assert.match(src, /const factSnippetContext = \{ normalizedText: normalizedFactSnippet \}/);
  assert.match(src, /sentenceFactualTokenMetrics\(context\.query, authoritySnippet, queryDerived\.normalizedSentenceFactualTokens, authoritySnippetContext\)/);
  assert.match(src, /sentenceFactualTokenMetrics\(context\.query, factSnippet, queryDerived\.normalizedSentenceFactualTokens, factSnippetContext\)/);
  assert.match(src, /phraseConceptCoverage\(context\.query, authoritySnippet, \{ \.\.\.phraseConceptContext, normalizedText: normalizedAuthoritySnippet \}\)/);
  assert.match(src, /phraseConceptCoverage\(context\.query, factSnippet, \{ \.\.\.phraseConceptContext, normalizedText: normalizedFactSnippet \}\)/);
  assert.match(src, /hasAccommodationContext\(authoritySnippet, authoritySnippetContext\)/);
  assert.match(src, /hasSection8Context\(factSnippet, factSnippetContext\)/);
  assert.match(src, /hasWrongfulEvictionLockoutContext\(factSnippet, factSnippetContext\)/);
  assert.match(src, /hasRepairNoticeContext\(authoritySnippet, authoritySnippetContext\)/);
  assert.match(src, /const sentenceStyle = queryDerived\.sentenceStyleReasoningQuery/);
  assert.match(src, /const phraseEvidenceQuery = queryDerived\.phraseEvidenceQuery/);
  assert.match(src, /const requiredMatches = 2/);
  assert.match(src, /function phraseConceptGuardPasses[\s\S]*normalizedText: cachedNormalizedSearchableText\(row, context\)/);
  assert.match(src, /function scoreRow[\s\S]*normalizedText: loweredSnippet/);
  assert.match(src, /function lexicalScore[\s\S]*precomputed\?: \{ normalizedGroups\?: string\[\]\[\]; terms\?: string\[\]; normalizedQuery\?: string; normalizedText\?: string \}[\s\S]*phraseConceptCoverage\(query, text, \{[\s\S]*normalizedGroups: precomputed\?\.normalizedGroups,[\s\S]*normalizedQuery,[\s\S]*normalizedText: lower/);
  assert.match(src, /const lexical = lexicalScore\(searchableText, context\.retrievalQuery, \{[\s\S]*normalizedGroups: queryDerived\.normalizedRetrievalPhraseConceptGroups,[\s\S]*terms: queryDerived\.retrievalLexicalTokens,[\s\S]*normalizedQuery: queryDerived\.normalizedRetrievalQuery/);
  assert.match(src, /function buildDocumentEvidenceSummary[\s\S]*normalizedText: aggregatedText/);
  assert.match(src, /function buildDocumentEvidenceSummary[\s\S]*phraseConceptCoverage\(context\.query, searchableText, \{ \.\.\.phraseConceptContext, normalizedText \}\)/);
  assert.match(src, /function representativeChunkDisplayScore[\s\S]*const queryDerived = getQueryDerivedContext\(context\)/);
  assert.match(src, /function representativeChunkDisplayScore[\s\S]*cachedNormalizedSearchableText\(candidate\.row, context\)/);
  assert.match(src, /function authorityPassageScore[\s\S]*const queryDerived = getQueryDerivedContext\(context\)/);
  assert.match(src, /function authorityPassageScore[\s\S]*cachedNormalizedSearchableText\(candidate\.row, context\)/);
  assert.match(src, /function authorityPassageScore[\s\S]*normalizedText\s*\n\s*\}\)/);
  assert.match(src, /function supportingFactAnchorDiagnostics[\s\S]*const queryDerived = getQueryDerivedContext\(context\)/);
  assert.match(src, /function supportingFactAnchorDiagnostics[\s\S]*cachedNormalizedSearchableText\(candidate\.row, context\)/);
  assert.match(src, /function supportingFactAnchorDiagnostics[\s\S]*normalizedText\s*\n\s*\}\)/);
  assert.match(src, /function pickSupportingFactCandidate[\s\S]*cachedCombinedSearchableText\(item\.candidate\.row, context\)/);
  assert.match(src, /function pickSupportingFactCandidate[\s\S]*cachedNormalizedSearchableText\(item\.candidate\.row, context\)/);
  assert.match(src, /function buildDecisionScopedCandidates[\s\S]*const queryDerived = getQueryDerivedContext\(context\)/);
  assert.match(src, /function buildDecisionScopedCandidates[\s\S]*!queryDerived\.structuralIntent[\s\S]*hasSevereExtractionArtifact\(row\.chunkText\)/);
  assert.match(src, /rowMatchesQueryGuard\(row, context\.query, context\)/);
  assert.match(src, /rowMatchesQueryGuard\(row, effectiveQuery, context\)/);
  assert.match(src, /function rowMatchesQueryGuard\(row: ChunkRow, query: string, context: SearchContext\): boolean[\s\S]*const normalizedText = cachedNormalizedSearchableText\(row, context\)/);
  assert.match(src, /function rowMatchesQueryGuard[\s\S]*hasHomeownersExemptionContext\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /function buildDecisionScopedCandidates[\s\S]*cachedCombinedSearchableText\(row, context\)/);
  assert.match(src, /function applyLowSignalStructuralGuard[\s\S]*const queryDerived = getQueryDerivedContext\(context\)[\s\S]*queryDerived\.structuralIntent/);
  assert.match(src, /const issueFamilyDecisionScopeSeedIds =[\s\S]*cachedCombinedSearchableText\(row, context\)/);
  assert.match(src, /function chunkMatchesIssueTerms[\s\S]*const queryDerived = getQueryDerivedContext\(context\)[\s\S]*const issueTerms = queryDerived\.issueTerms/);
  assert.match(src, /function chunkMatchesIssueTerms[\s\S]*const text = cachedNormalizedSearchableText\(row, context\)/);
  assert.match(src, /function chunkMatchesProceduralTerms[\s\S]*const queryDerived = getQueryDerivedContext\(context\)[\s\S]*const proceduralTerms = queryDerived\.proceduralTerms/);
  assert.match(src, /function hasStrongIssueEvidence\([\s\S]*context: SearchContext[\s\S]*cachedCombinedSearchableText\(row, context\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*const queryDerived = getQueryDerivedContext\(context\)[\s\S]*const normalizedQuery = queryDerived\.normalizedQuery/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*const normalizedQueryContext = \{ normalizedText: normalizedQuery \}/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*containsWholeWord\(searchableText, query, \{ normalizedText \}\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*if \(queryDerived\.section8UdQuery\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*if \(queryDerived\.packageSecurityQuery\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*if \(queryDerived\.homeownersExemptionQuery\)/);
  assert.match(searchQueryAnalysisSrc, /rentReductionQuery: isRentReductionQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(searchQueryAnalysisSrc, /nuisanceQuery: isNuisanceQuery\(context\.query, normalizedQueryContext\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*if \(queryDerived\.rentReductionQuery\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*if \(queryDerived\.nuisanceQuery\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*if \(queryDerived\.ownerMoveInFollowThroughRequired\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*hasOwnerMoveInPhrase\(normalizedQuery, normalizedQueryContext\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*containsWholeWord\(normalizedQuery, "omi", normalizedQueryContext\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*hasWrongfulEvictionPhrase\(normalizedQuery, normalizedQueryContext\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*containsWholeWord\(normalizedQuery, "awe", normalizedQueryContext\)/);
  assert.match(src, /function hasStrongIssueEvidence[\s\S]*containsWholeWord\(searchableText, "owner occupancy", \{ normalizedText \}\)/);
  assert.match(src, /hasMoldCollision\(searchableText, normalizedTextContext\)/);
  assert.match(src, /function leakWindowContextAdjustment\([\s\S]*precomputed\?: \{ normalizedQuery\?: string; normalizedText\?: string \}/);
  assert.match(src, /leakWindowContextAdjustment\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /hasHeatApplianceDrift\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /hasWaterHeaterDrift\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCapitalImprovementCostDrift\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /const normalizedTextContext = \{ normalizedQuery: queryDerived\.normalizedQuery, normalizedText \}/);
  assert.match(src, /hasWaterHeaterDrift\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /hasCapitalImprovementCostDrift\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /leakWindowContextAdjustment\(context\.query, searchableText, normalizedTextContext\)/);
  assert.match(src, /function habitabilityCoverageSignals\([\s\S]*precomputed\?: \{ normalizedText\?: string; requiredConditionSignals\?: string\[\] \}/);
  assert.match(src, /const requiredConditionSignals = precomputed\?\.requiredConditionSignals \?\? requiredHabitabilityPrimarySignals\(query\)/);
  assert.match(src, /const combinedHabitabilityText = `\$\{authorityText\} \$\{supportText\}`\.trim\(\)/);
  assert.match(src, /function orderDecisionFirst[\s\S]*const queryDerived = getQueryDerivedContext\(context\)/);
  assert.match(src, /function orderDecisionFirst[\s\S]*const evidence = buildDocumentEvidenceSummary\(candidates, context\)/);
  assert.match(src, /function orderDecisionFirst[\s\S]*const displayScored = sorted[\s\S]*representativeChunkDisplayScore\(candidate, context\)/);
  assert.match(src, /const layerTextContext = \{ normalizedText: layerText \}/);
  assert.match(src, /const authorityTextContext = \{ normalizedText: authorityText \}/);
  assert.match(src, /const supportTextContext = \{ normalizedText: supportText \}/);
  assert.match(src, /const decisionLayerSentenceStyle = queryDerived\.sentenceStyleReasoningQuery/);
  assert.match(src, /decisionLayerSentenceStyle && layers\.primaryAuthorityPassage/);
  assert.match(src, /decisionLayerSentenceStyle && layers\.primaryAuthorityPassage && layers\.supportingFactPassage/);
  assert.match(src, /function shouldRetrySupportingFactFallback[\s\S]*const queryDerived = getQueryDerivedContext\(context\)[\s\S]*queryDerived\.sentenceStyleReasoningQuery/);
  assert.match(src, /const habitabilityCoverageContext = \{ requiredConditionSignals: queryDerived\.requiredHabitabilitySignals \}/);
  assert.match(src, /habitabilityCoverageSignals\(authorityText, context\.query,[\s\S]*normalizedText: authorityText,[\s\S]*\.\.\.habitabilityCoverageContext/);
  assert.match(src, /habitabilityCoverageSignals\(combinedHabitabilityText, context\.query,[\s\S]*normalizedText: combinedHabitabilityText,[\s\S]*\.\.\.habitabilityCoverageContext/);
  assert.match(src, /hasWrongfulEvictionLockoutContext\(layerText, layerTextContext\)/);
  assert.match(src, /hasHarassmentContext\(layerText, layerTextContext\)/);
  assert.match(src, /hasLockBoxContext\(authorityText, authorityTextContext\)/);
  assert.match(src, /hasCameraPrivacyContext\(authorityText, authorityTextContext\)/);
  assert.match(src, /hasPackageDeliverySecurityContext\(layerText, layerTextContext\)/);
  assert.match(src, /isCameraPrivacyGenericLike:[\s\S]*queryDerived\.cameraPrivacyQuery &&/);
  assert.match(src, /isPackageSecurityGenericLike:[\s\S]*queryDerived\.packageSecurityQuery &&/);
  assert.match(src, /const combinedPoopLayerText = `\$\{authorityText\} \$\{supportText\}`\.trim\(\)/);
  assert.match(src, /hasStrongPoopDecisionContext\(combinedPoopLayerText, \{ normalizedText: combinedPoopLayerText \}\)/);
  assert.match(src, /hasWeakRodentPoopContext\(layerText, \{ normalizedText: layerText \}\)/);
  assert.match(src, /const layerNormalizedTextContext = \{ normalizedQuery: queryDerived\.normalizedQuery, normalizedText: layerText \}/);
  assert.match(src, /const layerLeakWindowAdjustment = leakWindowContextAdjustment\(context\.query, layerText, layerNormalizedTextContext\)/);
  assert.match(src, /if \(queryDerived\.wrongfulEvictionIssueQuery\) \{/);
  assert.match(src, /if \(queryDerived\.packageSecurityQuery\) \{/);
  assert.match(src, /if \(queryDerived\.cameraPrivacyQuery\) \{/);
  assert.match(src, /if \(queryDerived\.poopQuery\) \{/);
  assert.match(src, /hasConcretePhraseFactSignal\(searchableText, normalizedTextContext\)/);
  assert.match(src, /isGenericHousingServiceStandard\(searchableText, normalizedTextContext\)/);
  assert.match(src, /const aggregateConcretePhraseFacts = hasConcretePhraseFactSignal\(aggregatedText, \{ normalizedText: aggregatedText \}\)/);
  assert.match(src, /hasConcretePhraseFactSignal\(searchableText, \{ normalizedText \}\)/);
  assert.match(src, /function hasWrongContextForQuery[\s\S]*hasPetPolicyDrift\(normalizedText, \{ normalizedText \}\)[\s\S]*isCapitalImprovementBoilerplate\(normalizedText, \{ normalizedText \}\)/);
  assert.match(src, /isCapitalImprovementBoilerplate\(row\.chunkText, \{ normalizedText: cachedNormalizedChunkText\(row, context\) \}\)/);
  assert.match(src, /function chunkQualifiesForSection8UdDocumentSupport\([\s\S]*context: SearchContext[\s\S]*chunkMatchesSection8UdDocumentSupport\(row, section8UdDocumentSupportIds, context\)/);
  assert.match(src, /hasStrongIssueEvidence\(context\.query, row, issueTermHits, proceduralTermHits, context\)/);
  assert.match(src, /buildSection8UdDocumentSupportSet\(rows, context\)/);
  assert.match(src, /chunkQualifiesForSection8UdDocumentSupport\(row, diagnostics, section8UdDocumentSupportIds, context\)/);
  assert.match(src, /chunkMatchesIssueTerms\(row, context\)/);
  assert.match(src, /chunkMatchesProceduralTerms\(row, context\)/);
  assert.match(src, /const issueHits = queryDerived\.normalizedIssueTerms\.filter/);
  assert.match(src, /const proceduralHits = queryDerived\.normalizedProceduralTerms\.filter/);
});
